### PR TITLE
Environment fix 

### PR DESCRIPTION
**Pull request by ekatef**
The PR addresses recently reported environment troubles (see discussion [#1224](https://github.com/pypsa-meets-earth/pypsa-earth/discussions/1124)).

## Changes proposed in this Pull Request

A recent `1.4.1` release of `rasterio` seems to lead to some issues, while `1.3.11` works fine. The troubles may be windows-specific as the current runs of CI doesn't capture the problem while being rum on ubuntu and MacOS.

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by ekatef** [comment]
@davide-f could you please have a look? That is quite a urgent environment issue, and it would be great to merge it fast

**Comment by davide-f** [comment]
> @davide-f could you please have a look? That is quite a urgent environment issue, and it would be great to merge it fast

I can't reproduce it but feel free to merge as appropriate if urgent

**Review by davide-f — COMMENTED** [review]
I can't reproduce it but feel free to merge as appropriate if urgent

**Comment by ekatef** [comment]
> I can't reproduce it but feel free to merge as appropriate if urgent

I'm not able to reproduce it either, but we have multiple confirmations both of the problem itself, and the fact that this fix is working. My feeling is that it could make sense to add the fix, but I'd prefer to see CI happy before doing so 🙂

**Comment by ekatef** [comment]
CI breaks for pre-commit (which seems to be the issue of pre-commit itself not quite connected with this PR), but runs for both the workflows. In the meantime, we have some more reports confirming that the fix is needed, so I think it's really a good idea to merge it now

**Comment by AlexanderMeisinger** [comment]
I just double checked it again: 
- Using your fixed environment.yaml file
- Creating new environment
- Using fresh repository

Everything was working fine! The issue is solved.

**Pull request merged**
