### PR TITLE
Fix for missed ISO codes

### LINKED ISSUE #861: Empty GEGIS paths in build_demand_profiles
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [ ] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug
In the rule `build_demand_profiles` the GEGIS paths are empty, hence the rule fails. Not sure why.
Details: I am running the country Morocco `MA`.
Reproduce by run `solve_all_networks`, GADM clustering.

## Error Message

```bash
INFO:snakemake.logging:[Tue Sep 12 16:33:27 2023]
rule build_demand_profiles:
    input: networks/base.nc, resources/bus_regions/regions_onshore.geojson, resources/shapes/gadm_shapes.geojson
    output: resources/demand_profiles.csv
    log: logs/build_demand_profiles.log
    jobid: 18
    benchmark: benchmarks/build_demand_profiles
    reason: Missing output files: resources/demand_profiles.csv; Input files updated by another job: networks/base.nc, resources/bus_regions/regions_onshore.geojson
    resources: tmpdir=/tmp, mem_mb=3000, mem_mib=2862
INFO:snakemake.logging:rule build_demand_profiles:
    input: networks/base.nc, resources/bus_regions/regions_onshore.geojson, resources/shapes/gadm_shapes.geojson
    output: resources/demand_profiles.csv
    log: logs/build_demand_profiles.log
    jobid: 18
    benchmark: benchmarks/build_demand_profiles
    reason: Missing output files: resources/demand_profiles.csv; Input files updated by another job: networks/base.nc, resources/bus_regions/regions_onshore.geojson
    resources: tmpdir=/tmp, mem_mb=3000, mem_mib=2862

INFO:snakemake.logging:
/home/energyls/micromamba/envs/pypsa-earth/lib/python3.10/site-packages/pypsa/networkclustering.py:16: UserWarning: The namespace `pypsa.networkclustering` is deprecated and will be removed in PyPSA v0.24. Please use `pypsa.clustering.spatial instead`. 
  warnings.warn(
INFO:pypsa.io:Imported network base.nc has buses, lines, transformers
Traceback (most recent call last):
  File "/mnt/c/Users/scl38887/Documents/git/aldehyde/workflow/subworkflows/pypsa-earth-sec/pypsa-earth/.snakemake/scripts/tmpn6hqqqgy.build_demand_profiles.py", line 229, in <module>
    build_demand_profiles(
  File "/mnt/c/Users/scl38887/Documents/git/aldehyde/workflow/subworkflows/pypsa-earth-sec/pypsa-earth/.snakemake/scripts/tmpn6hqqqgy.build_demand_profiles.py", line 155, in build_demand_profiles
    gegis_load = xr.open_mfdataset(load_paths, combine="nested")
  File "/home/energyls/micromamba/envs/pypsa-earth/lib/python3.10/site-packages/xarray/backends/api.py", line 1003, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
```

### PR DESCRIPTION
**Pull request by ekatef**
# Closes #861 

Adds ISO code for Morocco into the OSM config

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by ekatef** [comment]
With the fix for Morocco, the list of ISO2 codes missed in our `osm_config` looks as follows:

```python
    iso2                                          name
4     AI                                      Anguilla
8     AQ                                    Antarctica
13    AW                                         Aruba
14    AX                                 Åland Islands
25    BL                              Saint Barthélemy
26    BM                                       Bermuda
29    BQ              Bonaire, Sint Eustatius and Saba
33    BV                                 Bouvet Island
38    CC                       Cocos (Keeling) Islands
44    CK                                  Cook Islands
52    CW                                       Curaçao
53    CX                              Christmas Island
73    FO                                 Faroe Islands
80    GG                                      Guernsey
82    GI                                     Gibraltar
86    GP                                    Guadeloupe
89    GS  South Georgia and the South Sandwich Islands
91    GU                                          Guam
94    HK                                     Hong Kong
95    HM             Heard Island and McDonald Islands
103   IM                                   Isle of Man
105   IO                British Indian Ocean Territory
110   JE                                        Jersey
123   KY                                Cayman Islands
140   MF                    Saint Martin (French part)
147   MO                                         Macao
148   MP                      Northern Mariana Islands
149   MQ                                    Martinique
151   MS                                    Montserrat
162   NF                                Norfolk Island
166   NO                                        Norway
174   PF                              French Polynesia
179   PM                     Saint Pierre and Miquelon
180   PN                                      Pitcairn
187   RE                                       Réunion
198   SH  Saint Helena, Ascension and Tristan da Cunha
200   SJ                        Svalbard and Jan Mayen
202   SL                                  Sierra Leone
210   SX                     Sint Maarten (Dutch part)
213   TC                      Turks and Caicos Islands
215   TF                   French Southern Territories
219   TK                                       Tokelau
231   UM          United States Minor Outlying Islands
238   VG                      Virgin Islands (British)
239   VI                         Virgin Islands (U.S.)
242   WF                             Wallis and Futuna
245   YT                                       Mayotte
```
It looks like currently only island countries and Antarctica are not into the list configuration list.

NB: a code of Norway has been misinterpreted during the current analysis being automatically transformed to `False`. However, `"NO"` is included into `config_osm`.

**Comment by davide-f** [comment]
Thanks Katia for the great check and highly needed :D

As a little comment, may be good to ensure all 193 UN countries are in the list. I think that would be important but also fast, what do you think?

We have the "UnitedNations" entry that should contain all of them.
May be good to check that (1) they are 193 and (2) that our config osm contains all of them.
Should be few lines luckily

**Comment by ekatef** [comment]
> Thanks Katia for the great check and highly needed :D
> 
> As a little comment, may be good to ensure all 193 UN countries are in the list. I think that would be important but also fast, what do you think?
> 
> We have the "UnitedNations" entry that should contain all of them. May be good to check that (1) they are 193 and (2) that our config osm contains all of them. Should be few lines luckily

Yeah, absolutely! `cc = coco.CountryConverter(); un_iso2 = cc.UNas("ISO2")` does the magic. Thank you so much for the hint, Davide :D

I'll do a comparison shortly and suggest fixes if needed.

**Comment by ekatef** [comment]
@davide-f You were absolutely right regarding a check. Sierra Leone has been missed, while being a UN country. Fixed now.

So, currently we have all 193 UN countries in `osm_config`, and additionally `'NC', 'PS', 'NU', 'XK', 'PR', 'VA', 'TW', 'GL', 'GF', 'FK', 'AS', 'EH'`= `'New Caledonia', 'Palestine', 'Niue', 'Kosovo', 'Puerto Rico', 'Vatican', 'Taiwan', 'Greenland', 'French Guiana', 'Falkland Islands', 'American Samoa', 'Western Sahara'`

**Comment by davide-f** [comment]
Cool! Amazing check @ekatef :D
Since you have the code ready, as mentioned above, what about "UnitedNations"?
It is in the continent_regions entry.
It may be nice to contain all 193 UN countries, may be good to check as well.
I cannot add the comment on that line in github as it is not modified...
After that this PR can be merged :)

**Comment by ekatef** [comment]
> Cool! Amazing check @ekatef :D Since you have the code ready, as mentioned above, what about "UnitedNations"? It is in the continent_regions entry. It may be nice to contain all 193 UN countries, may be good to check as well. I cannot add the comment on that line in github as it is not modified... After that this PR can be merged :)

It has been not difficult to find by `"UnitedNations"` :) Thanks a lot for the hint and the idea!

Both `read_osm_config("continent_regions")["UnitedNations"]` and country_converter UN list have 193 countries, and there is no difference between both lists.

**Comment by davide-f** [comment]
Super! :D
Thanks @ekatef , merging :)
I'm ignoring the error that is not related to this PR.

**Comment by ekatef** [comment]
> Super! :D Thanks @ekatef , merging :) I'm ignoring the error that is not related to this PR.

Thank you @davide-f :)

**Pull request merged**
