### PR TITLE
dc_type to dc_types

### PR DESCRIPTION
**Pull request by finozzifa**
# Closes # (if applicable).

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by ekatef** [comment]
Great @finozzifa! Let's wait until CI is successful and ready to merge after :)

**Comment by davide-f** [comment]
Interesting; I'm wondering why these issues were not captured by the CI.
It may be useful to update the CI to avoid these issues in the future

**Comment by ekatef** [comment]
> Interesting; I'm wondering why these issues were not captured by the CI. It may be useful to update the CI to avoid these issues in the future

Absolutely agree :) I'd merge this PR and open an issue to track CI advancements. Would you agree?

**Comment by davide-f** [comment]
Ok :)

**Comment by ekatef** [comment]
Thanks a lot @finozzifa! Merged :)

Have opened #1016 to track CI coverage. Feel free to investigate it, if you can be interested.

**Comment by finozzifa** [comment]
I will be happy to once I am done with #501 :)

**Pull request merged**
