### PR TITLE
Enable parallel computing with new dask version.

### LINKED ISSUE #396: Enable parallel computing with dask version
## Describe the feature you'd like to see
See more on: https://github.com/PyPSA/pypsa-eur/pull/384

### PR DESCRIPTION
**Pull request by pz-max**
# Closes https://github.com/pypsa-meets-earth/pypsa-earth/issues/396

## Changes proposed in this Pull Request
Enable parallel computing with new dask version. Fixex e.g. dask for renewable potential computations. **The code does not break.** However, I am still getting some weird logging: 

```
INFO:distributed.core:Removing comms to tcp://127.0.0.1:36793
INFO:distributed.batched:Batched Comm Closed <TCP (closed) Scheduler connection to worker local=tcp://127.0.0.1:35539 remote=tcp://127.0.0.1:52422>
Traceback (most recent call last):
  File "/home/max/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/home/max/.local/lib/python3.10/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/home/max/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/distributed/comm/tcp.py", line 269, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
```

Any suggestions? Think we can keep it in to stay on same base as EUR

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.

### CODE REVIEW

**Comment by davide-f** [comment]
Hello @pz-max ! What is the status of this PR?
Moreover, does the computational time change with and without this change?

**Comment by pz-max** [comment]
@davide-f, thanks for checking the status. I find the above described dask logging stuff a bit irritating. Nevertheless, happy to merge to stay on base with the EUR folks. Having dask working correctly is our aim. Adding now release notes. I didn't check for speed ups atm as the Eur folks did that already saying it is much faster.

Feel free to merge

**Comment by davide-f** [comment]
Mmmm do you have a message example of the messages?
Do we improve performances?

**Comment by pz-max** [comment]
Above is the message example & performance improvement is reported on the tagged issue which reference to PyPSA-Eur

**Comment by pz-max** [comment]
@davide-f merging after approval at weekly meeting

**Pull request merged**
