### PR TITLE
Add description on custom_powerplants use

### PR DESCRIPTION
**Pull request by carlosfv92**
*Added some additional lines in the commented section of the build_powerplants.py file, with some comments on how to allow the proper configuration/formating of a custom_powerplants.csv file that can be used in the buil_powerplants rule

# Closes # (if applicable).

## Checklist

- [x ] I consent to the release of this PR's code under the GPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by pz-max** [comment]
Hi @carlosfv92 ,
Thanks for the contribution. The documentation string is automatically used to compile the documentation. Your current contribtuion looks like this: image

I would recommend compiling the documentation locally. We have some documentation how to do this [here](https://pypsa-earth.readthedocs.io/en/latest/tutorial.html#compile-the-documentation-locally). I observed some issue with the docs and will raise in a moment a PR on your fork :+1:

**Comment by pz-max** [comment]
@carlosfv92 , please review and accept this PR https://github.com/carlosfv92/pypsa-earth-BO/pull/2 (will be automatically added here when you accept)

**Review by pz-max — APPROVED** [review]
looks good now. Thanks for the contribution @carlosfv92 :)

**Comment by carlosfv92** [comment]
Happy to help!

**Pull request merged**
