### PR TITLE
Finozzifa remove zenodo na

### PR DESCRIPTION
**Pull request by finozzifa**
# Closes # (if applicable).

## Changes proposed in this Pull Request

Remove https://sandbox.zenodo.org/records/13539/files/natura_wpda_CC0.zip?download=1 from bundle_config.yaml

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by ekatef** [comment]
Hey @finozzifa, could you please explain the purpose of this PR?

As a comment, `natura-wdpa` file is a pre-compiled raster which contains the information on the protected area. You can check the details on that under [pre-calculated datasets](https://pypsa-earth.readthedocs.io/en/latest/data_workflow.html#pre-calculated-datasets) in pypsa-earth docs. So, the data are definitely needed.

Have you observed any troubles accessing the link? As far as I can see, it is working properly.

**Comment by finozzifa** [comment]
Hey @ekatef , it was requested by @davide-f :)

**Comment by ekatef** [comment]
> Hey @ekatef , it was requested by @davide-f :)

@finozzifa, thanks for letting know. Could you please add some more details on purpose of the proposed changes? Generally, that is a very good idea to keep track of things in the discussions to the issues.

Are there any NAs in `natura-wdpa` file?

**Comment by ekatef** [comment]
Ahh, I see: a link to `natura_wdpa` seems to be mis-placed!! Nice catch 😄 
It looks like a zenodo link to `natura_wdpa` should be placed here, under `zenodo` url:

https://github.com/pypsa-meets-earth/pypsa-earth/blob/c1d4b993dc52d1f22a46efab983bcef5289afb95/configs/bundle_config.yaml#L187-L196

@finozzifa could you please check it? 🙏🏽 And also to fix the comment which seems to be wrong?

**Review by davide-f — COMMENTED** [review]
Many thanks @finozzifa :D
Merging :)

**Pull request merged**
