### PR TITLE
Add env caching and recombine individual OS CI files.

### PR DESCRIPTION
**Pull request by euronion**
This PR aims to improve the performance of subsequent CI calls on the same day.
It works by caching the `conda` environment, such that it is not recreated every time the CI runs, but only on a daily basis.

If the `environment.yaml` is updated, the CI will only register the update on the next day OR when the `CACHE_NUMBER` in `ci.yaml` is manually changed.

As a side effect this PR also recombines the `ci.yaml` files `ci-linux-mac.yaml` and `ci-windows.yaml` back into a single file while incoporating the fix introduced in 0fd4f59d4549b14ccbe048213866d6ca5d70c0ee .

PR based on https://github.com/PyPSA/pypsa-eur/pull/303 .

## Checklist

- [n/a] I tested my contribution locally and it seems to work fine.
- [n/a] Code and workflow changes are sufficiently documented.
- [n/a] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [n/a] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [n/a] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [n/a] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes.

### CODE REVIEW

**Comment by euronion** [comment]
@davide-f : Was the restriction `ipopt<=3.11.1` for windows necessary? For PyPSA-EUR we run windows/linux/macos on `ipopt<3.13.3` without issues. In our case the problem came from `ipopt<=3.13.3` in the `environment.yaml`, but with `ipopt<3.13.3` we had no issues.

If it is all the same for you and the CI runs with `ipopt<3.13.3` I'd propose the merge. We'd get rid of the additional ci file and have all ci tests back into one file again.

**Comment by davide-f** [comment]
> @davide-f : Was the restriction `ipopt<=3.11.1` for windows necessary? For PyPSA-EUR we run windows/linux/macos on `ipopt<3.13.3` without issues. In our case the problem came from `ipopt<=3.13.3` in the `environment.yaml`, but with `ipopt<3.13.3` we had no issues.
> 
> If it is all the same for you and the CI runs with `ipopt<3.13.3` I'd propose the merge. We'd get rid of the additional ci file and have all ci tests back into one file again.

Awesome contribution! Yeah if without the = works np!
The contribution looks fine and super useful!

**Comment by euronion** [comment]
Ok, great :)

The CI is failing though. I'm not sure if it is related to the PR though, seems to be an issue during databundle retrieveal.

**Comment by davide-f** [comment]
The CI works, except windows that went on idle.
I'd like a green light on both at least once before giving the green light, as before the CI was working on both Linux and windows (badges not updated for some reason though...)

**Comment by euronion** [comment]
Ok, after restarting the windows CI also passes successfully. RTM. :)

**Pull request merged**
