### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by energyLS**
Added new timing to README.md for sector-coupled model meeting

"  - Sector-coupled model development: every week Thursday 09:00-10:00 (UK time)"

### CODE REVIEW

**Comment by davide-f** [comment]
Hi @energyLS , thanks for noticing that issue!

I'd have two comments:
1. the current format lists the meetings like 1) Demand 2) AI and 3) Data Workflow; to stick to the current format you may add a 4) meeting, including below the timing. Given the increasing number of meetings, you may also propose a [table-like format](https://stackoverflow.com/questions/39378020/how-to-display-table-in-readme-md-file-in-github) now or in the future.
2. linter is failing because of a pre-existing issue; may you be so kind to fix the linter issue?
    As you can see in the report, the problem is related to the line 10 that is too long [you can see the report by clicking on 
    "Details" next to the failing linter option above].
    ``` batch
    2022-01-19 09:35:48 [INFO]   File:[/github/workspace/README.md]
    2022-01-19 09:35:48 [ERROR]   Found errors in [markdownlint] linter!
    2022-01-19 09:35:48 [ERROR]   Error code: 1. Command output:
    ------
    /github/workspace/README.md:10:401 MD013/line-length Line length [Expected: 400; Actual: 427]
    ------
    ```
    You may move "In 2022 we will focus on Earth wide expansion. Stay tuned and join our mission - We look for users, co-developers and leaders!" to line 11 to fix that.

**Comment by pz-max** [comment]
@energyLS any news on the status here?

**Comment by pz-max** [comment]
Hi @energyLS we close the PR. ( to much conflict and updates necessary)
Maybe you want to create a new one updating the times?

**Comment by energyLS** [comment]
Hi @pz-max, yes I will create a new one with hopefully less conflicts tomorrow

**Pull request closed without merging**
