### PR TITLE
Update documentation with the cleaned history

### PR DESCRIPTION
**Pull request by ekatef**
That is an improved version of #602 built on a cleaned fork of main (@davide-f  thanks a lot for providing proper spells for it!)

This update is intended to improve clarity and usability of our documentation and is mainly based on inputs from @yerbol-akhmetov and @davide-f. (Yerbol and Davide, thanks a lot for an insightful discussion!)

The suggested fixes contain:

- revision on natura.tiff usage to account for the recent developments;
- clarifications on cutout usage;
- improvement of explanations on data clean-up.

Checklist
 

- [ ] I tested my contribution locally and it seems to work fine.
- [ ]  Code and workflow changes are sufficiently documented.
- [ ]  Newly introduced dependencies are added to envs/environment.yaml and envs/environment.docs.yaml.
- [ ]  Changes in configuration options are added in all of config.default.yaml and config.tutorial.yaml.
- [ ]  Add a test config or line additions to test/ (note tests are changing the config.tutorial.yaml)
- [ ]  Changes in configuration options are also documented in doc/configtables/*.csv and line references are adjusted in doc/configuration.rst and doc/tutorial.rst.
- [ ]  A note for the release notes doc/release_notes.rst is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Review by davide-f — APPROVED** [review]
Good to me :) I'd merge if you have finished here

**Comment by ekatef** [comment]
Thanks @davide-f!

If you don't mind I'd be happy to add a couple points about time settings as discussed in #609  which seem to be well aligned the current content. However, if you feel like it'd be better to create another PR for that, I'm absolutely fine with it :)

**Comment by davide-f** [comment]
Ok! Then I'll wait ;)

**Comment by davide-f** [comment]
@ekatef given #612, can this PR be merged or shall we wait?

**Comment by ekatef** [comment]
@davide-f not yet :) In #612 @asv365 is addressing fine structure of `doc/configuration.rst` (previously some sections were captured from the wrong fragments).

Here we need a couple of additions to clarify which snapshot values are appropriate when customising the model. Sorry for the delay, will try to add these explanations today

**Comment by ekatef** [comment]
@davide-f added the promised points. If you approve these additions, I think this PR can be merged

**Comment by pz-max** [comment]
Let's talk at today's weekly about this PR. Looks good to me @ekatef

**Review by pz-max — APPROVED** [review]

**Pull request merged**
