### PR TITLE
add 'all' wildcard to solve_network

### LINKED ISSUE #819: Running the 'all' wildcard in solve_network returns error, add a "min" wildcard to select the minimum number of clusters
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

As discussed, using the `all` wildcard when clustering the network does work well. However doing the same when trying to solve the networks returns the following error

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
ERROR:snakemake.logging:InputFunctionException in rule solve_network in file /home/adminuser/toms_test/pypsa-earth/Snakefile, line 677:
Error:
  ValueError: invalid literal for int() with base 10: 'all'
Wildcards:
  simpl=
  clusters=all
  ll=copt
  opts=1H
Traceback:
  File "/home/adminuser/toms_test/pypsa-earth/Snakefile", line 672, in memory
```

Need's further investigation as it might be an easy fix and it's a useful wildcard. I also had a quick peruse of the documentation and could not find it there. I think it's worth documenting.

### PR DESCRIPTION
**Pull request by Tomkourou**
# Closes #819 

## Changes proposed in this Pull Request

Adds a fix so that the 'all' wildcard works for the solve_network rule.

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [x] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [x] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by Tomkourou** [comment]
@davide-f could you expand on what you mean about the 'min' wildcard.

**Comment by davide-f** [comment]
> @davide-f could you expand on what you mean about the 'min' wildcard.

Sure and thanks for the interest!
I'll add comment on the issue

**Comment by davide-f** [comment]
@Tomkourou sorry for jumping in, but for some analyses I needed this feature urgently.
Happy to have your comments on it and improve it further :D
If interested, you could focus on your parallel PR in https://github.com/pypsa-meets-earth/pypsa-earth/pull/773 :)

What do you think?

**Comment by davide-f** [comment]
Merging, we can improve it in subsequent PRs in case :)

**Pull request merged**
