### PR TITLE
add tech_colors

### PR DESCRIPTION
**Pull request by doneachh**
# Closes # (if applicable).

## Changes proposed in this Pull Request
To get this running, we need some additional tech_colors in our config:
https://github.com/pypsa-meets-earth/documentation/pull/87

## Checklist

- [ ] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by doneachh** [comment]
@energyLS please review!

**Review by davide-f — COMMENTED** [review]
Hello :)
Clearly I leave comments to Leon; it seems that some entries are kind-of duplicated, basically the only difference is the capital letters and values are not consistent thorught the dictionary.
Is this something we should do after or before the merge in your opinion?

**Comment by doneachh** [comment]
@davide-f before the merge -> would need it for this notebook: https://github.com/pypsa-meets-earth/documentation/pull/87

**Comment by doneachh** [comment]
@davide-f removed the double entries :)

**Review by davide-f — COMMENTED** [review]
Hello!
do you mind dropping ac, dc and load ac?
I think you could use AC line, HVDC links and load instead, what do you think?
With that, I think the pr can be merged :)

**Comment by davide-f** [comment]
Closed in favor of https://github.com/pypsa-meets-earth/pypsa-earth/pull/1037

**Pull request closed without merging**
