### PR TITLE
Improve earth coverage

### LINKED ISSUE #556: Taiwan demand data bug
## Checklist
- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

I use "TA" (Taiwan) in the config.yaml (default).
Running `snakemake -j1 solve_all_networks` did not run because data was missing -> `ssp2-2.6/2030/era5_2013/Asia.nc`
Downloading the demand data manually solved it: https://zenodo.org/record/6569890#.Y7avu6fP1Qo

There may be some issues with the data interface:
- https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/scripts/retrieve_databundle_light.py
- https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/configs/bundle_config.yaml

### PR DESCRIPTION
**Pull request by davide-f**
# Closes #556 

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [x] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by ekatef** [comment]
After some checking of `clean_osm_data` outputs for the tutorial case, it looks like the filtering criteria currently works too strong for OSM data quality (unless I have some troubles with reproducibility which also can be the case). A picture for `base.nc` currently looks like that with interconnected parts highlighted:

image

The reason of the network disintegration seems to be dropping NAs by [filter_circuits( )](https://github.com/davide-f/pypsa-earth/blob/635ad7cf253b5729b037cbf7081c03c85c0c1392/scripts/clean_osm_data.py#L218) which leaves only very few lines from a set available via OSM, as for the most lines not circuits information is available

That is a bit strange as previously the revised `clean_osm_data` has worked perfectly well, including the tutorial case...

@davide-f, do you have any ideas on what could go wrong?

**Comment by davide-f** [comment]
Mmmm it may make sense and actually the fix I inserted here may be wrong.
I'll crosscheck it further.
By the way, that issue of bus is still of interest as a fix for properly addressing countries with isolated nodes and arbitrary values of drop/merge thresholds

**Comment by ekatef** [comment]
Absolutely agree that #554 definitely needs to be addressed (and quite fast :) ), but it looks like some additional safety checks/warnings should be implemented as a part of such a fix. As far I can deduce, this issue arises when a network is reduced to some non-interconnected clusters which in some cases might be not an expected topology

**Comment by davide-f** [comment]
The issue of the image appeared because the astype(str) had not to be placed where I placed here.
It disrupts the procedure and I added a comment now.
Indeed having nans in the circuits is used to properly interpret them as 1 (default value) but when nan values are converted into strings, they are converted into "nan" (string type) that is no more nan. This has implications into the logic used to clean the circuits.
I added a comment to remind that

**Comment by ekatef** [comment]
> The issue of the image appeared because the astype(str) had not to be placed where I placed here. It disrupts the procedure and I added a comment now. Indeed having nans in the circuits is used to properly interpret them as 1 (default value) but when nan values are converted into strings, they are converted into "nan" (string type) that is no more nan. This has implications into the logic used to clean the circuits. I added a comment to remind that

@davide-f 
Thanks a lot for the explanation! Anyway, it was very good to have such disconnected geometry for investigating #554 :)

**Comment by davide-f** [comment]
RTR

**Comment by davide-f** [comment]
@pz-max Added the config option to specify the base configuration file into the scenario diff configs into configs/scenario

**Comment by pz-max** [comment]
@davide-f `snakemake -j1 run_tests` is not working. Can you look into this?

I am getting the following error:
```
Traceback (most recent call last):
  File "/home/max/code/pypsa-earth/.snakemake/scripts/tmp4w1j1bc9.add_electricity.py", line 779, in <module>
    attach_hydro(n, costs, ppl)
  File "/home/max/code/pypsa-earth/.snakemake/scripts/tmp4w1j1bc9.add_electricity.py", line 437, in attach_hydro
    assert missing_c.empty, (
AssertionError: 'resources/custom/renewable_profiles/profile_hydro.nc' is missing inflow time-series for at least one bus: NG.27_1
```

- If the CI passes, I would merge.

**TODO**, maybe in a new issue in case the CI does pass. It would be nice to use `run_tests` in the linux CI such that CI & local testing is the same. The

**Review by pz-max — APPROVED** [review]
Merge if CI passes. If CI does not pass, see comment above.

**Comment by davide-f** [comment]
CI passes, I'm merging.
Though the issue you found is interesting and links to known problem of another issue.
I'm referring it into that.
How to reproduce that problem?
Please add into the other issue any information may be valuable.

**Pull request merged**
