### PR TITLE
fix: :bug: Fix IDs of 9 countries, using the smallest geometry that contains them

### PR DESCRIPTION
**Pull request by AndreCNF**
## Changes proposed in this Pull Request

Maps 9 countries' ISO Alpha 2 codes to working IDs. These countries would fail otherwise. The new IDs were chosen via a `geopandas` `contains` operation, selecting the smallest geometry from `get_geom_sitemap` that fully contains the country.

e.g.
```python
# load PyPSA Earth's GeoDataFrame
eo_gdf = get_geom_sitemap()
# find the smallest geometry that contains a country
country = failed_countries[0]
country_aws_gdf = naturalearth_gdf.loc[naturalearth_gdf[COUNTRY_ID_COLUMN] == country]
matches_gdf = eo_gdf.loc[eo_gdf.contains(country_aws_gdf.iloc[0].geometry)]
matches_gdf["area"] = matches_gdf.area
matches_gdf.sort_values(by="area", ascending=True, inplace=True)
matches_gdf
```

## Checklist

- [X] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [X] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Review by davide-f — COMMENTED** [review]
Thanks Andre for the contribution.
Indeed the codes were in the old pypsa-earth code but not ported.

As comments, do you need these codes for your study?

As first comments, Macau and HongKong may not be needed as special regions within China.
For the other regions, I see that they may be useful

**Comment by AndreCNF** [comment]
> As comments, do you need these codes for your study?

Yes, we're running models over every country in the world at TransitionZero and we've noticed issues for these 9 countries.

**Review by davide-f — CHANGES_REQUESTED** [review]
Thanks for the Contribution!
Please check out the format of yaml, the commas "," at the end of the rows are not needed.
That leads to issues with the CI.

Moreover, I'm ok with adding this entries but to be on the same page, they represent administrative territories.
It is better to revise the terms appropriately for the enty geofk to ISO that we are editing.

Many thanks and looking forward! :D feel free to interact with the community on discord as well :)

**Review by davide-f — APPROVED** [review]

**Comment by davide-f** [comment]
Many thanks for the contribution!
Ready to merge :D congratulations, you will soon be a new contributor to the community :)

**Pull request merged**
