### PR TITLE
Fix solar slope and add wind correction factor for wake effects

### PR DESCRIPTION
**Pull request by pz-max**
## Changes proposed in this Pull Request
Solar potential were out of order. The current solar profiles are generated for north Europe (slope facing southwards).
The proposed config adjustments are a bug fix that gives more realistic solar potentials (slope=0). Future work should generate locational dependent slope factors.

Additionally, a correction factor was applied as in PyPSA-Eur to represent wake effects.

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by pz-max** [comment]
@davide-f solar potential was quite underestimated. Merging this after the check.

**Comment by euronion** [comment]
Any particular reason to use fixed `slope=0` and not `latitude_optimal` for `pv`?

**Comment by pz-max** [comment]
Awesome! It was just a quick fix. Didn't know it exist. Is this something which could change in PyPSA-EUR too?

**Comment by euronion** [comment]
You'd have to ask @coroa , it was initially `latitude_optimal` and later changed to fixed slope and orientation: https://github.com/PyPSA/pypsa-eur/commit/b4dcbbbd62a5d96d0dce66051bd752b96c4dd963 back in 2018. Maybe he remembers why it was changed in PyPSA-EUR . And maybe the same reason also applies here for Africa?

**Pull request merged**
