### PR TITLE
Change the default country to Nigeria (NG) so that the default config…

### PR DESCRIPTION
**Pull request by asv365**
… file runs smoothly

# Closes # (if applicable).

## Changes proposed in this Pull Request
Change the default country in the config.default.yaml file to Nigeria, as Africa was not working. This seems to be caused by a recent updated: download_osm_data has been moved into a separate package (earth_osm), which is causing little discrepancies.

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by pz-max** [comment]
@asv365 , what is the issue with `earth_osm`? Do you have an error message?

**Comment by asv365** [comment]
@pz-max I don't really now what the issue with earth_osm was. The error message I was getting when running with the original config.default.yaml, which has "Africa" as a country, is attached. @davide-f was aware of problems with Senegal or Gambia. 
See also the post in Discord/support "PyPSA Earth tutorial: ModuleNotFoundError: No module named 'earth_osm'"

[error.txt](https://github.com/pypsa-meets-earth/pypsa-earth/files/10570712/error.txt)

**Comment by pz-max** [comment]
Now there is the open PyPSA-Earth developer meeting on Discord.
We will talk about this PR:
- Fix earth_osm issue
- Reduce the config.default to a lower selection

**UPDATE:**
We agreed in the weekly to:
- reduce country from `countries: ["africa"]` to  `countries: ["NG", "BJ"]`
- reduce [`clusters: 55`](https://github.com/pypsa-meets-earth/pypsa-earth/blob/4019a9f1df6dd248ed34ba8a7adad771a728bc0e/config.default.yaml#L21) to `10`.
- adjust the [comment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/4019a9f1df6dd248ed34ba8a7adad771a728bc0e/config.default.yaml#L25) in the `config.default`. One suggestion is: `# Can be replaced by continent ['africa'] or user-specific region, see more at https://pypsa-earth.readthedocs.io/en/latest/configuration.html#top-level-configuration`
- Update the documentation: https://pypsa-earth.readthedocs.io/en/latest/configuration.html#top-level-configuration . There is no need to list all the two-letter code in Africa. We can simply say any `two-letter code on earth` (60% are working, the team works on making it 100%), or any [continent](https://github.com/pypsa-meets-earth/pypsa-earth/blob/4019a9f1df6dd248ed34ba8a7adad771a728bc0e/scripts/config_osm_data.py#L598), or any [user-specific region](https://github.com/pypsa-meets-earth/pypsa-earth/blob/4019a9f1df6dd248ed34ba8a7adad771a728bc0e/scripts/config_osm_data.py#L462-L463)

**Comment by asv365** [comment]
Thanks @pz-max, I think this is ready for review.

**Comment by pz-max** [comment]
@asv365 fantastic. Thanks for the critical suggestion and 
welcome as a GitHub contributor :)

**Pull request merged**
