### PR TITLE
Update_ppmatching

### LINKED ISSUE #689: Add GEM data to ppm config
## Describe the feature you'd like to see
Currently, PyPSA-Earth uses only a limited amount of available powerplant data:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/313ef0b9434df49d7725f6e17e11b74d73800171/configs/powerplantmatching_config.yaml#L17-L29

Let's try to add the existing global gas powerplant tracker database:
https://powerplantmatching.readthedocs.io/en/latest/api/powerplantmatching.data.GGPT.html

In future, we might want to add also the [coal powerplant data ](https://github.com/PyPSA/powerplantmatching/issues/80)and the GEM solar + wind data

### PR DESCRIPTION
**Pull request by Tomkourou**
# Closes #689.

## Changes proposed in this Pull Request
Adds GEM datasets to the powerplantmatching config
## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
Nice contribution!
It would be nice to test the benefits of this PR with few non-EU countries.
Some sample cases may be:
- the tutorial ["NG", "BJ"]
- 1 or 2 other countries you may be interested in. Egypt may be nice to check as in past studies the capacities were a bit weird but feel free to address any also non necessarily in Africa

**Comment by davide-f** [comment]
Given the length of the PR, I'd merge this with squash and merge unless there are comments, once few checks above have been performed

**Comment by Tomkourou** [comment]
Here are some results for the standard tutorial run ["NG", "BJ"] and ["EG"] seperately, where original is defined as [OSM, GEO, GPD] and with GEM is defined as [original, GBPT,GGPT,GCPT,GGTPT,GNPT,GSPT,GWPT,GHPT]. 

Here are the differences by FuelType:

# For Nigeria and Benin

| Technology | Original   | With GEM  | Difference |
|------------|------------|-----------|------------|
| CCGT       | 1472.09895 | 1724.5    | 17%        |
| Hard Coal  | 0          | 4829.5    | NA         |
| Hydro      | 1905.41401 | 2638      | 38%        |
| OCGT       | 6021.93048 | 12577.306 | 109%       |
| Oil        | 2187.62506 | 20        | -99%       |
| Total      | 11587.0685 | 21789.306 | 88%        |

image


The change in Oil can be almost entirely explained by two plants, Egbin and Sapele (in Nigeria) which were reclassified as gas turbines. 


All the changes happened in NG. Capacities in Benin come from two powerplants and are unchanged. 


# For Egypt 
| Technology  | original   | with GEM   | Difference |
|-------------|------------|------------|------------|
| CCGT        | 3233.58475 | 31387      | 871%       |
| Hard Coal   | #N/A       | 15240      | #N/A       |
| Hydro       | 2768.38284 | 5225.32264 | 89%        |
| Nuclear     | #N/A       | 1194       | #N/A       |
| OCGT        | 342.215987 | 20599.6409 | 5919%      |
| Oil         | 29759.4727 | 9484.17481 | -68%       |
| Grand Total | 36103.6562 | 83130.1384 | 130%       |


image

The decline in OCGT can be explained by the disappearance of one powerplant: [Kuriemat Iscc Egypt] is no longer in the dataset. A new Kuriemat has been added with a much larger capacity (10x) that is classified as a CCGT.

**Comment by davide-f** [comment]
Interesting, results look quite different and we may have some duplication maybe?
https://www.usaid.gov/powerafrica/nigeria 

Could you repeat the analysis with only the GEM databases?

To do that, it should be relatively easy: comment the lines in the ppl config on GEP/GPD of pypsa- earth and repeat the workflow from build power plants onwards. The tutorial is enough for that

**Comment by Tomkourou** [comment]
> Interesting, results look quite different and we may have some duplication maybe? https://www.usaid.gov/powerafrica/nigeria
> 
> Could you repeat the analysis with only the GEM databases?
> 
> To do that, it should be relatively easy: comment the lines in the ppl config on GEP/GPD of pypsa- earth and repeat the workflow from build power plants onwards. The tutorial is enough for that

## Nigeria and Benin only using GEM

| FuelType    | Capacity [MW] |
|-------------|---------------|
| CCGT        | 1684          |
| Hard Coal   | 4829.5        |
| Hydro       | 2638          |
| OCGT        | 11015         |
| Grand Total | 20166.5       |

This is the installed capacity according to Ember: 
image

However the wikipedia page on Nigerian power does include a 1200MW coal powerplant 
-> https://en.wikipedia.org/wiki/List_of_power_stations_in_Nigeria

**Comment by Tomkourou** [comment]
# Egypt with GEM only 

| Row Labels  | Sum of Capacity |
|-------------|-----------------|
| CCGT        | 31327           |
| Hard Coal   | 15240           |
| Hydro       | 5178            |
| Nuclear     | 1194            |
| OCGT        | 20383.2         |
| Grand Total | 73322.2         |


vs EMBER power capacity estimates: 

image

**Comment by davide-f** [comment]
Thanks @Tomkourou for the contribution! :)
Ready to merge!

**Pull request merged**
