### PR TITLE
Update to numpy 1.24 and shapely 2

### LINKED ISSUE #561: Fix deprecation to remove numpy restriction - numpy<1.24
The workflow should work without the environment restriction:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/fa799bf0723496a3ac5ec50feb9a2ffe2876d758/envs/environment.yaml#L29

### PR DESCRIPTION
**Pull request by davide-f**
# Closes #561 

## Changes proposed in this Pull Request
Fix numpy and shapely 2.

Note: with the new release, some weird warnings appear in build_bus_regions:
`/home/davidef/miniconda3/envs/pypsa-earth-new/lib/python3.10/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)`

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [x] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
This issue is related to shapely/GEOS, see https://github.com/shapely/shapely/issues/1345

It seems that with current implementation of the packages, in particular GEOS 3.11.1, when an empty polygon is the result of the intersection a warning is (unexpectedly) thrown.
If we want that behaviour to disappear, we need to limit the GEOS version or we keep it as is and see if with new releases that issue gets fixed.

This problem will be fixed in GEOS 3.11.2 within shapely as stated in the PR, but it will take some time (order of months)

**Comment by davide-f** [comment]
No release note is necessary I think

**Comment by pz-max** [comment]
@davide-f is the numpy restriction necessary? It's not a breaking change; hence we could just lift the restriction or not?
https://numpy.org/devdocs/release/1.24.0-notes.html

**Comment by davide-f** [comment]
> @davide-f is the numpy restriction necessary? It's not a breaking change; hence we could just lift the restriction or not? https://numpy.org/devdocs/release/1.24.0-notes.html

Agree, done: forcepushed the branch to overwrite the commit

**Comment by davide-f** [comment]
I think it would be safe to keep shapely >= 2 instead

**Pull request merged**
