### PR TITLE
Change of config file for Bolivia and dont ignore config file

### PR DESCRIPTION
**Pull request by hannotteadele**
# Closes # (if applicable).

## Checklist

- [ ] I consent to the release of this PR's code under the GPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by ekatef** [comment]
Hello @hannotteadele and thanks for your PR! Nice to see that you are interested in modeling Bolivia :)

Could you please clarify a bit what is the aim of the changes you propose in the PR? Currently `config.yaml` is not tracked as it is problem-specific

**Comment by hannotteadele** [comment]
Hello! I’m very sorry I made a bad manipulation and I wanted to simply merge it into my own repository. I’m just learning how to use GitHub and SmartGit in parallel and I should have misunderstood something. I’m sorry for the disturbing.

Have a nice day.

Adèle Hannotte
***@***.***

**Comment by ekatef** [comment]
> Hello! I’m very sorry I made a bad manipulation and I wanted to simply merge it into my own repository. I’m just learning how to use GitHub and SmartGit in parallel and I should have misunderstood something. I’m sorry for the disturbing.
> 
> Have a nice day.
> 
> Adèle Hannotte
> ***@***.***

@hannotteadele no worries, it happens 🙂

Anyway, nice to meet you, Adèle! Don't hesitate to contact us whenever you have any questions regarding the model

Best wishes,
Katia

**Comment by hannotteadele** [comment]
Thank you very much ! Nice to meet you too ☺️ 

I’m struggling with the adaptation of the model for the hydroelectricity part but I asked my questions in the discord. 

Wishes 


Adèle Hannotte
***@***.***

**Pull request closed without merging**
