### PR TITLE
fix: remove unused argument from load_GDP

### PR DESCRIPTION
**Pull request by ollie-bell**
# Closes # (if applicable).

## Changes proposed in this Pull Request
Remove unused `countries_codes` argument from `load_GDP` function  in `build_shapes.py` script.

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by ollie-bell** [comment]
This unused argument was not being considered when calling the function. Because these are passed as positional arguments, they were not being passed as intended (e.g. `update` was taking the value of `out_logging`)

https://github.com/pypsa-meets-earth/pypsa-earth/blob/62691b6171dc6cc9ca5cefa9d52079c046c3b1a9/scripts/build_shapes.py#L697

**Comment by davide-f** [comment]
Many thanks @ollie-bell !
Would you like to add a minor release note? :)

**Comment by ollie-bell** [comment]
> Many thanks @ollie-bell ! Would you like to add a minor release note? :)

Done!

**Comment by davide-f** [comment]
Welcome among contributors @ollie-bell :D

**Pull request merged**
