### PR TITLE
Update cleaning file

### PR DESCRIPTION
**Pull request by davide-f**
I propose a cleaned version of the cleaning script, as discussed in #28 

Please comment, modify and adjust as you please.

Davide

### CODE REVIEW

**Comment by davide-f** [comment]
Note: I debugged the file and crosscheched the outputs of _substations and _lines cable that are identical (except lines for the filtering criterion voltage > or >= threshold) [I use the latter, while the original file was with the former; yet it is fast to change]

**Review by pz-max — APPROVED** [review]
Great job Davide. The code looks clean and useful.

**Comment by pz-max** [comment]
Hi @davide-f, we only need to correct the linting errors. Linting is there to keep our code uniform and easy to read.
If you click on the "X" marked Lint Code Base details, then you will see where you have linting issues.
Could you please correct them? (let me know if you have any question)

**Comment by davide-f** [comment]
I made some changes based on the lint log, but there must be something left for sure; please, could you run the flows so that I can proceed?

**Pull request merged**
