### PR TITLE
Implement HVDC lines into the model

### LINKED ISSUE #286: Verify HVDC lines
## Verify and validate HVDC lines

HVDC lines should be addressed and verified along the code.
For simplicity assumptions, lines have been assumed to be mostly AC, but this assumption can no longer be considered.

The code shall be revised to remove assumptions of AC lines, especially when we want to go global.

Such main assumptions are made in the [build_osm_network script](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/scripts/build_osm_network.py); generally the "DC" status is set to false by default but that shall be revised
DC nodes shall be distinguished from AC nodes.

In particular, in the function merge_stations_lines_by_station_id_and_voltage, AC nodes shall be distinguished from DC nodes
https://github.com/pypsa-meets-africa/pypsa-africa/blob/dff3930706a967e842e9e7427f7c01b0532bcf0d/scripts/build_osm_network.py#L422

### PR DESCRIPTION
**Pull request by ekatef**
The PR is intended to resolve #286 using the [following approach ](https://github.com/pypsa-meets-africa/pypsa-africa/issues/286#issuecomment-1137434530)proposed by @davide-f (thank you for the brilliant tutorial!)

## Checklist

- [ ] I tested my contribution locally and it seems to work fine:
     - [ ] on regional scale
     - [ ] on the whole model
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
Good that you opened the PR! :) Maybe since it is a work in progress, you may convert it into draft (in github you can do that using the url on the top right part of the page, next to the title of the PR)

I've seen that the git history is a bit messy.
A good way would be to start from a clean branch. It is possible to do so by:
```
git remote add upstream https://github.com/pypsa-meets-africa/pypsa-africa
git fetch upstream
git checkout
git reset --hard upstream/main
git push --force 
```

This procedure should hard reset the branch to the public version of the repo

**Comment by ekatef** [comment]
@davide-f, thank you for checking! Yes, of course it was supposed to be a draft. Just changed it.

And many thanks for the instructions about git. I was looking for a way to make it cleaner.

**Comment by ekatef** [comment]
**UPD** A branch clean-up has worked perfectly.  @davide-f, thank you so much for git-hints! Then I'll close this PR to open its copy #348 as it seems to be the only way changing the branch.

**Comment by davide-f** [comment]
Ok as you prefer! Then I close the PR.
Good job! I've seen you have already worked on it :)

**Comment by ekatef** [comment]
@davide-f, thank you! That's an interesting task :) 
Currently I'm a bit struggling with powerplantsmatching when setting the model. Could you please have a look on the issue #349?

**Pull request closed without merging**
