### PR TITLE
Fix tutorial settings

### PR DESCRIPTION
**Pull request by ekatef**
Set `build_natura_raster` to `false` for tutorial to simplify work with the tutorial.

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by ekatef** [comment]
Currently CI is failing as the workflow doesn't retrieve `natura.tiff` for some reason.

**Comment by davide-f** [comment]
The tutorial is expected to have build_natura_tiff true.
The shape for building the natura is available in the databundle (it is a custom square I drew XD)
Why is this needed?

**Comment by ekatef** [comment]
> The tutorial is expected to have build_natura_tiff true. The shape for building the natura is available in the databundle (it is a custom square I drew XD) Why is this needed?

Ahh, thanks a lot for the explanation! Haven't been aware that building natura.tiff for the tutorial implies a simplified approach... 

The reason of the PR was to address some support requests on how to deal with building a custom `natura.tiff` for a full-scale model. So, I though that there could be a sub-optimal setup of the tutorial, but that is obviously the feature, not a bug. Sorry for the misunderstanding, I didn't mean to offend the config! 😊 

Thanks for checking, @davide-f!

**Comment by davide-f** [comment]
No problem, a pleasure :D

**Pull request closed without merging**
