### PR TITLE
Add voronoi cell plot and create plot function

### PR DESCRIPTION
**Pull request by pz-max**
## New plot example:

solar-gridcell
solar-cell
output

## Checklist
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by pz-max** [comment]
@davide-f I just updated the build_cutout, land-availability and build_renewables notebooks over the past days. Feel free to check them out :+1: . I show the illustrations in the notebook. As mentioned, in future we clean the history and put such nice plot examples in another repository & maybe add a submodule or whatever makes sense.

Feel free to merge this PR.

**Comment by davide-f** [comment]
Please @pz-max , may you check the files? they seem corrupted and pre-commit is also failing unfortunately

**Comment by pz-max** [comment]
Weird error. I reverted with the below approach now: https://stackoverflow.com/questions/610208/how-to-retrieve-a-single-file-from-a-specific-revision-in-git

The easiest way is to write:

```bash
git show HASH:file/path/name.ext > some_new_name.ext
```

where:

    HASH is the Git revision SHA-1 hash number
    file/path/name.ext is name of the file you are looking for
    some_new_name.ext is path and name where the old file should be saved

**Comment by pz-max** [comment]
ready to merge @davide-f

**Comment by davide-f** [comment]
Super!
I'd suggest to stick to use the same EPSG values though.
Is there a specific reason why you used "epsg:3395"? It is eurocentric, though it should not lead to major issues

**Comment by pz-max** [comment]
Good spot. Just a historic relict from the EU stuff. Will fix it by applying your area crs from your new PR

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by davide-f** [comment]
@pz-max Is this ready to merge?

**Comment by pz-max** [comment]
> @pz-max Is this ready to merge?

Yes

**Pull request merged**
