### PR TITLE
Add a fix for missing column with empty generators dataframe

### PR DESCRIPTION
**Pull request by ekatef**
Quick fix for #704 

## Changes proposed in this Pull Request

Added "weight" column to n.generators dataframe to match with a structure expected by `PyPSA::aggregategenerators`

## Checklist

- [x] I consent to the release of this PR's code under the GPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
Thanks @ekatef for the check and clarification to see where the problem arises.
I'll repeat the test also on TV to see what's going on and eventually

**Comment by davide-f** [comment]
@ekatef Thanks for the check.
With your help, we found that the problem is related to the fact that the cutout for TV is basically empty and that leads no generator to be installed even when the clip values are 0.0.
#709 fixes this and enables TV to run.

Now the question is: shall we also add this fix?
- benefit: the workflow runs also in that case
- disadvantage: do we want the workflow to run with no generators? That would lead to trivial optimizations or errors down the chain.

A proposal may be to merge #709 and #704 so that instead of adding the weight column, a logger error is thrown if the weight column is not available to say that something is wrong and most likely no generators are available.
What do you think?

If you are interested, feel free to do cherry-pick from the other PR and finalize.
If you may have problems with the cherry-pick, I can manually add the changes here. Let me know :)

**Comment by ekatef** [comment]
@davide-f absolutely agree that the error should be thrown in case the simulation is basically empty. However, it's possible that there is no `weight` column but the simulation still makes sense, in particular there is hydro generators (treated as storage) or/and conventional generators.

The question I'd think about is if we want to allow simulations when conventional generators only are in the system. Is it a proper use case, keeping in mind dispatch-only functionality #710?

**Comment by davide-f** [comment]
Yep, then feel free to merge the two PRs or I can do that as well :)

**Comment by ekatef** [comment]
Go ahead please 🙂 
I'll be happy to see it finalised

**Comment by davide-f** [comment]
As discussed, this PR is merged into #714.
I'm closing this PR

**Pull request closed without merging**
