### PR TITLE
Global natura

### LINKED ISSUE #468: Fix natura tiff default file
## Describe the Bug

Currently the default natura tiff is based on EPSG 3035 and it shall be revised to:
1. have global scope
2. has the standard ESRI reference  in agreement to our workflow

In performing the study, I am encountering this environment issue that is under fixing.

## Error Message

```bash
ERROR 1: PROJ: proj_create_from_database: /home/davidef/miniconda3/envs/pypsa-earth/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 1 whereas a number >= 2 is expected. It comes from another PROJ installation.
Traceback (most recent call last):
  File "rasterio/crs.pyx", line 775, in rasterio.crs.CRS.from_user_input
  File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_ogrerr
rasterio._err.CPLE_BaseError: OGR Error code 6
```

### PR DESCRIPTION
**Pull request by davide-f**
# Closes #468 

## Changes proposed in this Pull Request
This PR completes #470 and includes a real global natura raster file

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [x] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
I've successfully created a natura.tiff with EPSG CRS.
I'm running now again the wf with the ESRI representation to check if some problem occurrs

**Comment by ekatef** [comment]
And that is the line which swaps latitude and longitude

[raster = ~geometry_mask(shapes.geometry, out_shape[::-1], transform)](https://github.com/pypsa-meets-earth/pypsa-earth/blob/89135406d2415989b18a9e80dc247f4e8368b08c/scripts/build_natura_raster.py#L196)

Not sure why did the changes I have introduced in the PR to fix it have disappeared after merging...

**Comment by davide-f** [comment]
> And that is the line which swaps latitude and longitude
> 
> [raster = ~geometry_mask(shapes.geometry, out_shape[::-1], transform)](https://github.com/pypsa-meets-earth/pypsa-earth/blob/89135406d2415989b18a9e80dc247f4e8368b08c/scripts/build_natura_raster.py#L196)
> 
> Not sure why did the changes I have introduced in the PR to fix it have disappeared after merging...

Should I remove the -1 then? Can you point to your original branch? (If still existing)

**Comment by ekatef** [comment]
Even [::-1] :)
replacing `out_shape[::-1]` with `out_shape`

https://github.com/ekatef/pypsa-earth/blob/b551dc12e068c8096cb220ce979bc8d10796b5b0/scripts/build_natura_raster.py#L198

**Comment by davide-f** [comment]
Yeah, obviously. Thanks :)
Let's give it another round and let's see xD

**Comment by pz-max** [comment]
> Even [::-1] :) replacing `out_shape[::-1]` with `out_shape`
> 
> https://github.com/ekatef/pypsa-earth/blob/b551dc12e068c8096cb220ce979bc8d10796b5b0/scripts/build_natura_raster.py#L198

Katia which PR was that? Was it this one https://github.com/pypsa-meets-earth/pypsa-earth/pull/464. Any other PR that didn't merge correctly? The PR was one of the things you copied from BEFORE the big clean up to AFTER the big clean up. I fear that it might end up in Nirvana (wrong git hash or so). 

When you created the new PR, did you manually add the new lines or copy & paste the whole folder and the new script?

**Comment by ekatef** [comment]
@pz-max, yes, it was #464 and no it was only this one :)

Don't remember exactly how it was created in after clean-up but most likely some file copy took place. Besides, it was obviously not a very good idea to commit the changes to the main without creating a branch for it

No problem, it happens :) I'll just re-create it from the local copy

**Comment by davide-f** [comment]
Habemus natura :D
image

I'll try to rerun it to check if we can avoid the rounding (e.g. 180 instead of 179.99). That will take 1-2 days more.

When I use the compare_shapes notebook @ekatef there are some weird problems, most likely due to reprojections, but in qgis the tiff seems good.

**Comment by ekatef** [comment]
@davide-f, serdeczne gratulacje :) Bravo, molto ben fatto!

Thanks for the hint regarding QGIS. Probably, that's a good idea to use it for spatial checking especially when working with rasters

**Comment by davide-f** [comment]
The approach seems working; tested for NG with full workflow
image

**Comment by davide-f** [comment]
The PR is a bit messy, due to the partially included PR, in case squash and merge.
@pz-max It is worth noticing the release_notes: I restored some lines of PR 466 and 471 that have been lost in the history; maybe due to some merge problems?
The two PRs seem work fine though. Let's keep in mind this to make sure anything bad appened after the merge (the two PRs are after the merge anyway) and when revising the PRs let's make sure git merges do not create problems

**Pull request merged**
