### PR TITLE
Fix CI for the updated environment [TESTING]

### PR DESCRIPTION
**Pull request by ekatef**
A manual downgrade of `numpy` version as `numpy 2.2.0` appears to have incompatibilities with `conda` which currently lead to troubles is #1232 

## Checklist

- [ ] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
I've experienced this issue locally.
It feels to me that there is miscoordination between conda and pip dependencies.
The long-term solution is to avoid dependencies in pip [and we are doing that]
A short-term solution could be to keep numpy installed in pip but with lower value.

Locally, I solved with pip install numpy={lower version}

It may be worth a try

**Review by davide-f — COMMENTED** [review]
I've had experienced this issue locally, sad this is not just my issue...
It feels to me that there is miscoordination between conda and pip dependencies.
The long-term solution is to avoid dependencies in pip [and we are doing that]
A short-term solution could be to keep numpy installed in pip but with lower value.

Locally, I solved with pip install numpy={lower version}

It may be worth a try

**Comment by ekatef** [comment]
Resolved with adding a restriction to `numpoly` version.

Have experimented with adding `highspy<1.8` and `tsam>=2.3.1` following PyPSA-Eur but don't think it's really related as those restrictions seem to be older than troubles with `numpy` (and didn't help anyway).

**Comment by ekatef** [comment]
Closing in favour of #1232

**Pull request closed without merging**
