### PR TITLE
update pypsa africa hydro according to pypsa europe

### PR DESCRIPTION
**Pull request by MPavicevic**
# Closes # (if applicable).

## Checklist

- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes.

### CODE REVIEW

**Comment by pz-max** [comment]
Hi @MPavicevic , are there any updates here? :)

**Comment by davide-f** [comment]
Hello @MPavicevic ,
Thank your for your contribution.
I was wondering if there are any updates on this PR and issue.
May you have questions?

**Comment by MPavicevic** [comment]
Dear Max and Davide,

Please accept my apology for not being able to work on this issue/PR. Currently I'm not in a position to work on any side-projects. 

Feel free to assign this issue to someone else.

I still hope to have the opportunity to work with you in the near future once things calm down a bit.

I hope for your understanding

**Comment by pz-max** [comment]
Hi @MPavicevic, no problem. Thanks for trying. Looking forward to a potential collab in future :)

**Pull request closed without merging**
