### PR TITLE
Output files with objective function value

### PR DESCRIPTION
**Pull request by finozzifa**
# Closes # (if applicable).

The pull request provides the initial ingredient for resolving https://github.com/pypsa-meets-earth/pypsa-earth/issues/495

## Changes proposed in this Pull Request

Add output files and output snippet for the objective function value

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by finozzifa** [comment]
The pull request does not propose an automatic check of the objective function value as part of the CI/CD, as it is not explicitly requested in #495.

**Review by davide-f — COMMENTED** [review]
Hello!

Great for the proposal :D
Personally, I'd like the objective to be only printed; not sure we need the output file in txt form as it is already available in the output pypsa network.
Unless you have a different vision.

With the textual format, I think the PR is ready to go. But let me know your thoughts :)

**Comment by finozzifa** [comment]
Hey @davide-f , thanks!!!

please proceed with merging it when you have time

**Comment by davide-f** [comment]
Maybe I have been clear my apologies.
Why are you proposing to save the results in a txt file?

I think it may be better to print them with logger.info.
That will print the results into screen and save the result in the log file.

This will also allow the easy check of the obviective value during review.
What do you think?

**Comment by finozzifa** [comment]
Hi @davide-f ,
sure I will restore the Snakefile and replace the outputs with a _logger.info_

**Comment by davide-f** [comment]
Great @finozzifa :D
Many thanks! As CI passes, this is merged :)

**Comment by davide-f** [comment]
Great @finozzifa :D
Merging :)

**Pull request merged**
