### PR TITLE
Improved parallelization of build_shapes

### LINKED ISSUE #574: Improve parallel capabilities of build_shapes
build_shapes takes a long time to compute due to the add_population procedure.
It may be interesting to perform and store some preprocessing for every country similarly to the download_osm_network. For example, store the partial dataframe of population for each country.

### PR DESCRIPTION
**Pull request by davide-f**
# Closes #574 

## Changes proposed in this Pull Request
A revised implementation of paallel capabilities of build_shapes to address parallelization even for a small set of countries.
Moreover, even for large sets, the proposed approach may be more desirable.

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
Surprisingly enough, I cannot reproduce the error... locally the PR works and major package versions (geopandas, shapely and gdal).

This seems a data corruption problem when retriving data from worldpop

**Comment by davide-f** [comment]
@pz-max Please, could you revise the PR when you have time?
Currently it is failing the CI but I think it is a weird problem, yet the core of the algorithm is not affected by that, so it is ready for revision

**Review by pz-max — APPROVED** [review]
Smart integration leveraging that each country has smaller shapes that can be parallelized

**Comment by davide-f** [comment]
Let's merge this only when CI works though

**Comment by pz-max** [comment]
In case it worked locally, this can be merged if you like.
Or we wait for the GADM shapes to be online for a successful test.
Up to you :)

**Pull request merged**
