### PR TITLE
add zenodo handler

### LINKED ISSUE #643: Add rule to automatically upload datakits to zenodo
This methodology can be used to create a snakemake rule to upload data to zenodo: [link](https://towardsdatascience.com/zenodopy-manage-zenodo-projects-from-python-aa7c36634c1d)

_Originally posted by @davide-f in https://github.com/pypsa-meets-earth/pypsa-earth/discussions/633_

More details to come, if anyone is interested, please comment :)

### PR DESCRIPTION
**Pull request by pz-max**
# Closes #643

## Changes proposed in this Pull Request
- Add `zenodo_handler.py` to upload and update data via API from code.
- Update zenodo links

Enables:
- massive, mutlifile data upload to zenodo via CLI
- automatic link update with update e.g. we could write in future automatically the bundle_config.yaml with the information

## Checklist

- [x] I consent to the release of this PR's code under the GPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by pz-max** [comment]
Ready for review

**Review by davide-f — APPROVED** [review]
Looks nice to me!
As a comment on the structure, these "non-workflow scripts" may be placed in a separate folder.
Currently, this is the 2nd or 3rd file that does not belong to the workflow.
It could be good to discuss about that.

The zenodo stuff for the CI is needed soon; the restructuring of the files to separate "non-workflow" scripts may be included in another PR if you prefer.

**Comment by pz-max** [comment]
Thanks for the review. The files are now in a `non_workflow` folder.
Feel free to merge if it is ok now @davide-f :)

**Comment by davide-f** [comment]
Merged :)

**Pull request merged**
