### PR TITLE
Fix workflow for countries with empty osm data

### LINKED ISSUE #641: Issues when countries do not have lines
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

When a country does not have lines (e.g. SB), the following error is thrown.
We do not manage the case when the lines dataframe is empty.

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
Traceback (most recent call last):
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmpkuici8ah.clean_osm_data.py", line 1003, in <module>
    clean_data(
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmpkuici8ah.clean_osm_data.py", line 814, in clean_data
    df_lines = gpd.read_file(input_files["lines"])
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/geopandas/io/file.py", line 259, in _read_file
    return _read_file_fiona(
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/geopandas/io/file.py", line 303, in _read_file_fiona
    with reader(path_or_bytes, **kwargs) as features:
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/fiona/env.py", line 457, in wrapper
    return f(*args, **kwds)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/fiona/__init__.py", line 335, in open
    colxn = Collection(
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/fiona/collection.py", line 234, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 587, in fiona.ogrext.Session.start
  File "fiona/ogrext.pyx", line 143, in fiona.ogrext.gdal_open_vector
fiona.errors.DriverError: 'resources/SB/osm/raw/all_raw_lines.geojson' not recognized as a supported file format.
```

### LINKED ISSUE #642: Non managed expection when clean_substations.geojson is empty
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

We don't manage the exeption when all_clean_substations.geojson is empty.
This may be revised and add a custom error message.
Indeed, when no clean_substations are available after cleaning it means that:
- when lines are available, then the option add line endings may be disabled and a prompt message should recommend to do so.
- Alternatively, if really no substations (and lines) are available, then pypsa-earth has nothing to optimize so the error may be understandable. A message should suggest to add manually nodes, such as using the future linkers

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
Traceback (most recent call last):
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmppbxf587l.build_osm_network.py", line 858, in <module>
    built_network(
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmppbxf587l.build_osm_network.py", line 730, in built_network
    buses = gpd.read_file(inputs["substations"])
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/geopandas/io/file.py", line 259, in _read_file
    return _read_file_fiona(
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/geopandas/io/file.py", line 303, in _read_file_fiona
    with reader(path_or_bytes, **kwargs) as features:
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/fiona/env.py", line 457, in wrapper
    return f(*args, **kwds)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/fiona/__init__.py", line 335, in open
    colxn = Collection(
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/fiona/collection.py", line 234, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 587, in fiona.ogrext.Session.start
  File "fiona/ogrext.pyx", line 143, in fiona.ogrext.gdal_open_vector
fiona.errors.DriverError: 'resources/GM/osm/clean/all_clean_substations.geojson' not recognized as a supported file format.
```

### LINKED ISSUE #735: Unexpected behaviour in clustering for Lithuania
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

When using PR #701 , an error appears for Lithuania.
During the clustering, for some reason the only link that is placed in Lithuania gets clustered into the same node and loses the bus0 and bus1 tags. Moreover, the build_year tag becomes nan and that triggers the error denoted in:
https://github.com/PyPSA/PyPSA/issues/637

This issue needs investigation.

To replicate, please use #701 using default configuration on countries: ["LT"] and clusters: [5]

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
Traceback (most recent call last):
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmp9bknsrmp.add_extra_components.py", line 242, in <module>
    n = pypsa.Network(snakemake.input.network)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pypsa/components.py", line 341, in __init__
    self.import_from_netcdf(import_name)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pypsa/io.py", line 644, in import_from_netcdf
    _import_from_importer(network, importer, basename=basename, skip_time=skip_time)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pypsa/io.py", line 794, in _import_from_importer
    import_components_from_dataframe(network, df, component)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pypsa/io.py", line 860, in import_components_from_dataframe
    dataframe[k] = dataframe[k].astype(static_attrs.at[k, "typ"])
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/generic.py", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 451, in astype
    return self.apply(
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 105, in _astype_nansafe
    return _astype_float_to_int_nansafe(arr, dtype, copy)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/dtypes/astype.py", line 150, in _astype_float_to_int_nansafe
    raise IntCastingNaNError(
pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
```

### PR DESCRIPTION
**Pull request by davide-f**
# Closes #642 , #641, #735

## Changes proposed in this Pull Request
Add methods to handle cases when data from osm are empty.
This PR is built on top of #654 

## Checklist

- [x] I consent to the release of this PR's code under the GPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [x] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
Here I dropped the REUSE precommit because when working locally I do have a modified version of .gitignore and that is not read by the REUSE linter.
Therefore, the REUSE checked also ignored files and thus it was impossible to do any commit.
Since version checking shall be done once in a while and may apply only new scripts, I preferred to drop it here

**Comment by pz-max** [comment]
> Here I dropped the REUSE precommit because when working locally I do have a modified version of .gitignore and that is not read by the REUSE linter.
> 
> Therefore, the REUSE checked also ignored files and thus it was impossible to do any commit.
> 
> Since version checking shall be done once in a while and may apply only new scripts, I preferred to drop it here

The reuse linting considers .gitignore. I also noted that it didn't always worked as intended, however, probably that was a mistake by the dev (me in this case). I made it work in the latest fix_earth PR.

I think if reuse is in the .pre-commit it won't hurt in case it works as intended. It's actually good, as we have one thing less to check (even though new file creation won't happen often)

**Comment by davide-f** [comment]
I'm locally using the changes in #714 , not yet committed here as that is a cojoint activity with @ekatef and may be nice to have a cojoint PR

**Comment by davide-f** [comment]
> > Here I dropped the REUSE precommit because when working locally I do have a modified version of .gitignore and that is not read by the REUSE linter.
> > Therefore, the REUSE checked also ignored files and thus it was impossible to do any commit.
> > Since version checking shall be done once in a while and may apply only new scripts, I preferred to drop it here
> 
> The reuse linting considers .gitignore. I also noted that it didn't always worked as intended, however, probably that was a mistake by the dev (me in this case). I made it work in the latest fix_earth PR.
> 
> I think if reuse is in the .pre-commit it won't hurt in case it works as intended. It's actually good, as we have one thing less to check (even though new file creation won't happen often)

I partially agree, but there is a problem:
Locally, I have folders backup, world and many results that are related to the world runs needed for papers and so on. To avoid problems, I have changed the .gitignore accordingly to avoid problems, but those changes are not committed.
REUSE ignores the files as specified in the gitignore in the repo, not the local version (it seems so).
Accordingly, every time I had to commit, REUSE was checking also those files that were locally ignored.
I had a ton of problems accordingly and I had alwas to go for no-verify using manual checks using precommit.

As a fix, I'll add to gitignore some additional folders to avoid such issue and keep the REUSE, but let's keep that into mind.

**Comment by pz-max** [comment]
@davide-f it should consider the local `.gitignore`. So, I tend to believe that we don't use the `.gitignore` properly. In this SO post, I can see various avenues that we could try: https://stackoverflow.com/questions/2545602/how-to-git-ignore-subfolders-subdirectories

**Comment by davide-f** [comment]
> @davide-f it should consider the local `.gitignore`. So, I tend to believe that we don't use the `.gitignore` properly. In this SO post, I can see various avenues that we could try: https://stackoverflow.com/questions/2545602/how-to-git-ignore-subfolders-subdirectories

I agree that REUSE should consider the local gitignore, but it didn't seem the case in the tests that I did.
To bypass the issue, I pushed a new gitignore that works in my case: I put most of my debug files into backup* folders

**Comment by davide-f** [comment]
With the combination of this PR and #714 All 193 countries are now running.
Some of them, however do not have a proper load from gegis as discussed in #707, however, that is not in the scope of this PR.

Priority should be given to merge #714 and then this PR can be merged.
Ideally, another complete country-wise run should be done before merging this PR but #714 is needed first.

**Comment by davide-f** [comment]
@pz-max or @ekatef  could you please revise this quickly so that we can also fix pre-commit without conflicts to this?
In #779 the fix to pre-commit is ready but we need this to be merged first.
Then, I can create a new PR with the fix applied to the new main

**Review by pz-max — APPROVED** [review]
Great changes and nothing to complain about

**Pull request merged**
