### PR TITLE
change cutout names in bundles

### LINKED ISSUE #758: Revision of bundle configs for compatibility purposes
## Describe the feature you'd like to see

The following bundle configs available in "configs/bundle_config.yaml" shall be revised as following:
1. "bundle_cutouts_africa": the file "africa-2013-era5.nc" shall be renamed into "cutout-2013-era5.nc"
2. "bundle_cutouts_tutorial_BW", "bundle_cutouts_tutorial_NGBJ", "bundle_cutouts_tutorial_MA": for each of this bundle, the file "africa-2013-era5-tutorial.nc" shall be renamed into "cutout-2013-era5-tutorial.nc"
3. "bundle_tutorial_BW", "bundle_tutorial_NGBJ", "bundle_tutorial_MA": for each tutorial data bundle, revise the folder "data/World**pop**" into "data/World**Pop**"

For each databundle mentioned above, the following shall be performed:
1. Download the corresponding zip file, using the url specified in the corresponding bundle config in the file "configs/bundle_config.yaml"
2. Unzip the folder
3. Apply the change according to the list described above
4. Zip again the folder using the python code available in "scripts/non_workflow/zip_folder"
5. Upload the file to google drive and share it to us; we will download and upload the file in the pypsameetsearth account to free your account and provide you with an updated gdrive link to finalize the PR
6. Open a PR that finalizes the changes

### PR DESCRIPTION
**Pull request by Tomkourou**
# Closes #758

## Changes proposed in this Pull Request

Change the bundle cutouts in bundle_config.yaml according to issue #758
## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by Tomkourou** [comment]
@davide-f all data bundles have been downloaded and the zip files have been named according to their corresponding bundle for clarity. 

You can find them here --> https://drive.google.com/drive/folders/18SyT9uYEEnsRyVMPmhDgTsGJ2URt-NGa?usp=share_link

**Comment by davide-f** [comment]
Thanks @Tomkourou for the PR that is indeed linked to #758 .
Unfortunately, to make this work, there is also the need to re-create the data packages for the tests and re-upload them in gdrive and zenodo.

As discussed in https://github.com/pypsa-meets-earth/pypsa-earth/issues/758, each cutout databundle shall be downloaded, unzipped, change the name of the file, and re-zipped using https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/scripts/non_workflow/zip_folder.py

Ideally, it would be awesome also to revise the tutorials data packages to revise the name of the worldpop folder.

Do you think you could take care of parts of this tasks? They shouldn't be too much time consuming.
Once the zip files are ready, you can upload them in gdrive and share with us; we will upload them in our shared folder to free your gdrive account and provide you with the links for the revised pr.

**Comment by davide-f** [comment]
Hello Tom :D
I've reuploaded all zip files, and below you can find the links:
- cutouts tutorial NGBJ: https://drive.google.com/file/d/1xnomHdXf_c5STrf7jtDiuRlN2zW0FSVC/view?usp=drive_link
- cutouts tutorial MA: https://drive.google.com/file/d/1j5v2f4E756jmDMa707QvdNJq3xM4bYUk/view?usp=drive_link
- cutouts tutorial BW: https://drive.google.com/file/d/1DDQAtnIDM0FNC3vCldfHeH__IpTbyIJt/view?usp=drive_link
- cutouts default africa: https://drive.google.com/file/d/1WHv5Dm1GtrDZj-AxJZd3T-NMIBXty3eV/view?usp=drive_link
- data tutorial NGBJ: https://drive.google.com/file/d/1Vb1ISjhy7iwTTZYeezGd6S4nLt-EDGme/view?usp=drive_link
- data tutorial MA: https://drive.google.com/file/d/1VGzE8ZJHAvAQ9X44QNSX4rH3QF7Yi37D/view?usp=drive_link
- data tutorial BW: https://drive.google.com/file/d/19IXvTD8gVSzgTInL85ta7QjaNI8ZPCCY/view?usp=drive_link

Could you please revise the gdrive links and temporarily comment the zenodo links for the corresponding bundles?
The goal is to test if the zip fully work and when that's proven, we can upload also them to zenodo and finalize it.
Many thanks @Tomkourou for the great contribution! :D

**Comment by Tomkourou** [comment]
Test successfully passed using the solve_all_networks rule for the following updated bundles:
- [x] cutouts tutorial NGBJ
- [x] cutouts tutorial MA
- [x] cutouts tutorial BW
- [x] cutouts default africa
- [x] data tutorial NGBJ
- [x] data tutorial MA
- [x] data tutorial BW

**Comment by Tomkourou** [comment]
Problem when running the MA workflow in the add_electricity rule. Not sure if it's related to the bundle update. I will check with the old version in a moment. 

```
WARNING:__main__:'resources/renewable_profiles/profile_hydro.nc' is missing inflow time-series for at least one bus: 164, 184, 213, 217, 261, 267, 277, 296, 300, 34, 372, 411, 423, 466, 87.Corresponding hydro plants are dropped, corresponding to a total loss of -1519.5932351567803MW out of 1647.5932351567803MW.
Traceback (most recent call last):
  File "/Users/adminuser/Documents/Coding/Tomkourou/pypsa-earth/.snakemake/scripts/tmp4qm71fgi.add_electricity.py", line 824, in <module>
    attach_hydro(n, costs, ppl)
  File "/Users/adminuser/Documents/Coding/Tomkourou/pypsa-earth/.snakemake/scripts/tmp4qm71fgi.add_electricity.py", line 487, in attach_hydro
    inflow.sel(plant=intersection_plants)
  File "/Users/adminuser/mambaforge/envs/pypsa-earth/lib/python3.10/site-packages/xarray/core/common.py", line 615, in assign_coords
    data.coords.update(results)
  File "/Users/adminuser/mambaforge/envs/pypsa-earth/lib/python3.10/site-packages/xarray/core/coordinates.py", line 172, in update
    self._update_coords(coords, indexes)
  File "/Users/adminuser/mambaforge/envs/pypsa-earth/lib/python3.10/site-packages/xarray/core/coordinates.py", line 388, in _update_coords
    dims = calculate_dimensions(coords_plus_data)
  File "/Users/adminuser/mambaforge/envs/pypsa-earth/lib/python3.10/site-packages/xarray/core/variable.py", line 3280, in calculate_dimensions
    raise ValueError(
ValueError: conflicting sizes for dimension 'name': length 1 on <this-array> and length 17 on {'name': 'name', 'time': 'time'}
[Thu Jul  6 10:33:41 2023]
INFO:snakemake.logging:[Thu Jul  6 10:33:41 2023]
Error in rule add_electricity:
    jobid: 6
    input: resources/renewable_profiles/profile_onwind.nc, resources/renewable_profiles/profile_offwind-ac.nc, resources/renewable_profiles/profile_offwind-dc.nc, resources/renewable_profiles/profile_solar.nc, resources/renewable_profiles/profile_hydro.nc, networks/base.nc, resources/costs.csv, resources/powerplants.csv, resources/shapes/gadm_shapes.geojson, data/hydro_capacities.csv, resources/demand_profiles.csv
    output: networks/elec.nc
    log: logs/add_electricity.log (check log file(s) for error details)
```

**Comment by Tomkourou** [comment]
Tutorial data for MA is working successfully with old cutouts. I will redo the MA cutouts.

**Comment by Tomkourou** [comment]
Fixed bundle cutout for MA. Tested with new google drive link and the workflow runs successfully. 

You can find the updated MA cutout here -> https://drive.google.com/file/d/10N_fk4sVotiKRv5za0cvxc1viw2uE5Gs/view?usp=share_link

**Comment by davide-f** [comment]
Great @Tomkourou ! :D

I've also updated the new MA cutout online at:
https://drive.google.com/file/d/1TW3ej9yJb6FVz53v1XnWmqhr5m3tXtcC/view?usp=drive_link
Tom, in the new commit that may include all changes, you may update the link as well.

Moreover, I believe the zip_folder script has been removed by mistake, that needs to be restored.

@pz-max we are ready to update the zips mentioned above in zenodo as well, so that we can finalize this PR.
I believe you did it last time, can you do that?

The tested links are those in the PR that should be (copy and paste from above + replacing the MA ones with the latest one):
- cutouts tutorial NGBJ: https://drive.google.com/file/d/1xnomHdXf_c5STrf7jtDiuRlN2zW0FSVC/view?usp=drive_link
- cutouts tutorial MA: https://drive.google.com/file/d/1TW3ej9yJb6FVz53v1XnWmqhr5m3tXtcC/view?usp=drive_link
- cutouts tutorial BW: https://drive.google.com/file/d/1DDQAtnIDM0FNC3vCldfHeH__IpTbyIJt/view?usp=drive_link
- cutouts default africa: https://drive.google.com/file/d/1WHv5Dm1GtrDZj-AxJZd3T-NMIBXty3eV/view?usp=drive_link
- data tutorial NGBJ: https://drive.google.com/file/d/1Vb1ISjhy7iwTTZYeezGd6S4nLt-EDGme/view?usp=drive_link
- data tutorial MA: https://drive.google.com/file/d/1VGzE8ZJHAvAQ9X44QNSX4rH3QF7Yi37D/view?usp=drive_link
- data tutorial BW: https://drive.google.com/file/d/19IXvTD8gVSzgTInL85ta7QjaNI8ZPCCY/view?usp=drive_link

**Comment by pz-max** [comment]
Awesome. I will do that on Friday morning!

**Comment by Tomkourou** [comment]
All links have been updated @davide-f :)

**Comment by davide-f** [comment]
Very good :)
Max will soon upload the files in zenodo and as a last step you can also revise those links.
After that, if the CI works, we can merge everything :)

**Comment by davide-f** [comment]
@Tomkourou please, also revise the config files to replace africa-* with cutout-* , that's why the CI is currently failing

**Comment by Tomkourou** [comment]
> @Tomkourou please, also revise the config files to replace africa-* with cutout-* , that's why the CI is currently failing

Done :)

**Comment by davide-f** [comment]
@Tomkourou Awesome! :D and the CI all passes, amazing :)
Have you also locally tested the africa default case?

**Comment by Tomkourou** [comment]
Re the error message when trying "Africa" in the config.yaml: 

```
ERROR:osm_data_extractor:IC not found. check view_region()
Traceback (most recent call last):
  File "/Users/adminuser/Documents/Coding/pypsa-earth/.snakemake/scripts/tmpryefoq9y.download_osm_data.py", line 112, in <module>
    eo.get_osm_data(
  File "/Users/adminuser/mambaforge/envs/pypsa-earth/lib/python3.10/site-packages/earth_osm/eo.py", line 97, in get_osm_data
    region_tuple_list = [get_region_tuple(rs) for rs in region_list]
  File "/Users/adminuser/mambaforge/envs/pypsa-earth/lib/python3.10/site-packages/earth_osm/eo.py", line 97, in <listcomp>
    region_tuple_list = [get_region_tuple(rs) for rs in region_list]
  File "/Users/adminuser/mambaforge/envs/pypsa-earth/lib/python3.10/site-packages/earth_osm/gfk_data.py", line 172, in get_region_tuple
    id = get_id_by_str(region_str)
  File "/Users/adminuser/mambaforge/envs/pypsa-earth/lib/python3.10/site-packages/earth_osm/gfk_data.py", line 161, in get_id_by_str
    raise KeyError(f'{region_str} not found. check view_region()')
KeyError: 'IC not found. check view_region()'
[Thu Jul 13 22:55:09 2023]
INFO:snakemake.logging:[Thu Jul 13 22:55:09 2023]
Error in rule download_osm_data:
    jobid: 15
    output: resources/osm/raw/all_raw_cables.geojson, resources/osm/raw/all_raw_generators.geojson, resources/osm/raw/all_raw_generators.csv, resources/osm/raw/all_raw_lines.geojson, resources/osm/raw/all_raw_substations.geojson
    log: logs/download_osm_data.log (check log file(s) for error details)
```

**Comment by davide-f** [comment]
@Tomkourou I'm debugging locally Africa and fixing the issue you are experiencing.
As it passes, the default Africa is to be considered validated :)

**Comment by davide-f** [comment]
Africa cutout tested successfully :) @pz-max you can proceed in uploading the zenodo files

**Comment by pz-max** [comment]
Upload done. Hope it runs through

**Comment by davide-f** [comment]
If it works feel free to merge :)

**Review by davide-f — APPROVED** [review]

**Pull request merged**
