### PR TITLE
Enable the use of a float value for the scale in load_options

### PR DESCRIPTION
**Pull request by AnasAlgarei**
## Changes proposed in this Pull Request
The aim of the PR is to enable the use of a float value for the scale in load_options in the config file.

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by AnasAlgarei** [comment]
This PR is raised because I faced an error when using a float value for the scale in load_options: "typeerror: can't multiply sequence by non-int of type 'float'". The PR is a simple fix for this error where only the column of "Electricity demand" is multiplied by the float value, the other string columns are not multiplied.

**Comment by davide-f** [comment]
Hey @AnasAlgarei awesome to see your first contribution.
The ci is unfortunately failing, but it is related to the fact that the config files (default tutorial and test) have not been changed according to the additional option that you proposed.
After doing that the ci should be working.

**Comment by AnasAlgarei** [comment]
> Hey @AnasAlgarei awesome to see your first contribution. The ci is unfortunately failing, but it is related to the fact that the config files (default tutorial and test) have not been changed according to the additional option that you proposed. After doing that the ci should be working.

Hey @davide-f! Thanks for your reply
I understand that I should change the config files then? but the only related change in the config files is the scale, and the PR works for both a float and an integer scale. Can we discuss this in the meeting tomorrow?

**Comment by pz-max** [comment]
@AnasAlgarei if you add the readme this PR is ready to merge :100:

**Comment by pz-max** [comment]
@AnasAlgarei you fix here a big. Float values couldn't be used in the past. GIving a hint in the release docs would be helpful. I merge this PR anyways if the CI is successful. Congrats on your first contribution :dancers:

**Comment by AnasAlgarei** [comment]
> @AnasAlgarei you fix here a big. Float values couldn't be used in the past. GIving a hint in the release docs would be helpful. I merge this PR anyways if the CI is successful. Congrats on your first contribution 👯

Great! Thanks for the hints @pz-max and @davide-f, I added a note in the release notes though, looking forward to future contributions 😊

**Pull request merged**
