### PR TITLE
Global natura

### LINKED ISSUE #468: Fix natura tiff default file
## Describe the Bug

Currently the default natura tiff is based on EPSG 3035 and it shall be revised to:
1. have global scope
2. has the standard ESRI reference  in agreement to our workflow

In performing the study, I am encountering this environment issue that is under fixing.

## Error Message

```bash
ERROR 1: PROJ: proj_create_from_database: /home/davidef/miniconda3/envs/pypsa-earth/share/proj/proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 1 whereas a number >= 2 is expected. It comes from another PROJ installation.
Traceback (most recent call last):
  File "rasterio/crs.pyx", line 775, in rasterio.crs.CRS.from_user_input
  File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_ogrerr
rasterio._err.CPLE_BaseError: OGR Error code 6
```

### PR DESCRIPTION
**Pull request by davide-f**
# Closes #468 

## Changes proposed in this Pull Request
This PR aims at:
- revising the workflow to make sure natura raster works
- fixing the default CRS of natura.tiff (currently it is EPSG:3035 that is less accurate for africa)
- create a general natura.tiff for the entire world

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
The CI cannot run now because the gadm website is down.

Last missing piece here is to create the global natura tiff (it is running now) and upload it in drive.

**Comment by davide-f** [comment]
PR ready to review

**Comment by davide-f** [comment]
This PR contains some errors.

Reposting from @ekatef 

@davide-f, unfortunately it looks like there are some troubles with applying the global `natura.tiff`. Coordinates transformation to any cylindrical projection ("EPSG:4326" or "EPSG:32663") gives the outer `natura.tiff` boundary as `POLYGON ((Infinity Infinity, Infinity Infinity, Infinity Infinity, Infinity Infinity, Infinity Infinity))` while building renewable profiles with Central Asia cutout leads to an error `Point outside of projection domain` (the full listing attached bellow).

That's a bit strange as the original raster boundary is `POLYGON ((-359000 -27057000, -359000 9020100, -18040100 9020100, -18040100 -27057000, -359000 -27057000))` which gives 36077100 to 17681100 with an aspect rasio 2/1 how it should be...

Just to be sure about coordinates definition:

https://github.com/davide-f/pypsa-earth/blob/036bcc8d67ed423743daf7b0549887b382e7b526/scripts/build_natura_raster.py#L98-L101

Should be here the limiting range be +/-180 deg the same both for `x` and `y` coordinates?

```bash
# ----------------------------------------------------
# error listing
# ----------------------------------------------------
INFO:snakemake.logging:rule build_renewable_profiles:
    input: networks/base.nc, resources/natura.tiff, data/copernicus/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif, data/gebco/GEBCO_2021_TID.nc, resources/shapes/country_shapes.geojson, resources/shapes/offshore_shapes.geojson, data/hydro_capacities.csv, data/eia_hydro_annual_generation.csv, resources/powerplants.csv, resources/bus_regions/regions_onshore.geojson, cutouts/casr-2018-era5.nc
    output: resources/renewable_profiles/profile_onwind.nc
    log: logs/build_renewable_profile_onwind.log
    jobid: 8
    benchmark: benchmarks/build_renewable_profiles_onwind
    reason: Missing output files: resources/renewable_profiles/profile_onwind.nc; Input files updated by another job: networks/base.nc, resources/bus_regions/regions_onshore.geojson, resources/shapes/offshore_shapes.geojson, resources/shapes/country_shapes.geojson, resources/powerplants.csv
    wildcards: technology=onwind
    resources: tmpdir=/var/folders/qn/vpndfm21795ckkq89np1ckp40000gn/T, mem_mb=20000

INFO:snakemake.logging:
Traceback (most recent call last):
  File "~Documents/_github_/pypsa-earth/.snakemake/scripts/tmpsjdn5q29.build_renewable_profiles.py", line 425, in <module>
    natura_gejson = rio.warp.transform_geom(
  File "~opt/miniconda3/envs/pypsa-africa/lib/python3.9/site-packages/rasterio/env.py", line 387, in wrapper
    return f(*args, **kwds)
  File "~opt/miniconda3/envs/pypsa-africa/lib/python3.9/site-packages/rasterio/env.py", line 612, in wrapper
    return f(*args, **kwds)
  File "~opt/miniconda3/envs/pypsa-africa/lib/python3.9/site-packages/rasterio/warp.py", line 109, in transform_geom
    return _transform_geom(
  File "rasterio/_warp.pyx", line 125, in rasterio._warp._transform_geom
  File "rasterio/_warp.pyx", line 76, in rasterio._warp._transform_single_geom
  File "rasterio/_err.pyx", line 215, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_AppDefinedError: Point outside of projection domain
[Thu Oct 13 22:23:50 2022]
INFO:snakemake.logging:[Thu Oct 13 22:23:50 2022]
Error in rule build_renewable_profiles:
    jobid: 8
    output: resources/renewable_profiles/profile_onwind.nc
    log: logs/build_renewable_profile_onwind.log (check log file(s) for error message)

ERROR:snakemake.logging:Error in rule build_renewable_profiles:
    jobid: 8
    output: resources/renewable_profiles/profile_onwind.nc
    log: logs/build_renewable_profile_onwind.log (check log file(s) for error message)

RuleException:
CalledProcessErrorin line 341 of ~Documents/_github_/pypsa-earth/Snakefile:
Command 'set -euo pipefail;  ~opt/miniconda3/envs/pypsa-africa/bin/python3.9 ~Documents/_github_/pypsa-earth/.snakemake/scripts/tmpsjdn5q29.build_renewable_profiles.py' returned non-zero exit status 1.
  File "~Documents/_github_/pypsa-earth/Snakefile", line 341, in __rule_build_renewable_profiles
  File "~opt/miniconda3/envs/pypsa-africa/lib/python3.9/concurrent/futures/thread.py", line 58, in run
ERROR:snakemake.logging:RuleException:
CalledProcessErrorin line 341 of ~Documents/_github_/pypsa-earth/Snakefile:
Command 'set -euo pipefail;  ~opt/miniconda3/envs/pypsa-africa/bin/python3.9 ~Documents/_github_/pypsa-earth/.snakemake/scripts/tmpsjdn5q29.build_renewable_profiles.py' returned non-zero exit status 1.
  File "~Documents/_github_/pypsa-earth/Snakefile", line 341, in __rule_build_renewable_profiles
  File "~opt/miniconda3/envs/pypsa-africa/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
WARNING:snakemake.logging:Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
ERROR:snakemake.logging:Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-10-13T220051.621624.snakemake.log
WARNING:snakemake.logging:Complete log: .snakemake/log/2022-10-13T220051.621624.snakemake.log
```

**Comment by ekatef** [comment]
Happy to assist! Anyway, I think the global `natura.tiff` will make the model much more user-friendly. That's not quite obvious to understand what goes inside the raster :)

**Comment by davide-f** [comment]
``There is something quite surprising: it seems like half of the globe is not covered
image

Anyway the crs conversion leads to issues.
I'll be running the build_natura_raster using geo_crs as a crs and see if problems still occur

For clarity, this is the cutout description i'm using
```yaml
atlite:
  nprocesses: 4
  cutouts:
    # geographical bounds automatically determined from countries input
    africa-2013-era5:
      module: era5
      dx: 0.3  # cutout resolution
      dy: 0.3  # cutout resolution
      # Below customization options are dealt in an automated way depending on
      # the snapshots and the selected countries. See 'build_cutout.py'
      time: ["2013-01-01", "2014-01-01"]  # specify different weather year (~40 years available)
      x: [-180, 180]  # manual set cutout range
      y: [-90, 90]    # manual set cutout range
```

**Pull request merged**
