### PR TITLE
Validate hydro capacities

### LINKED ISSUE #39: Integrating hydro reservoir capacities
To model hydro powerplants, we need data on:
- The power plants themselves: generation capacities (taken care of by powerplantmatching),
- The hourly inflow for each power plant (see #38), and
- The reservoir capacity for each powerplant (this issue).

Not all hydro power plants have a reservoir (run-of-river plants do not), but those that have reservoirs provide flexibility to the energy system by being able to shift generation in time.

As a starting point, we can investigate using the GRanD database (http://globaldamwatch.org/grand/). The data can be freely used, but note that the license doesn't allow us to redistribute the data. There may also be other suitable databases that we could use.

The main task for this issue is integrating the reservoir data (from e.g. GRanD) with our existing powerplant data (from powerplantmatching), and inflow modelling data (see #38).
- One option is to match by location, and assign reservoirs in GRanD to the closest available powerplant from powerplantmatching.
- Other options could also be consired. Does GRanD include generation capacities? Is its coverare good? If so, we could use it as "the" data for hydro power plants, instead of anything from powerplantmatching.

### LINKED ISSUE #108: build_renewable_profiles - offwind/hydro bugs
A couple of functions are commented in the `build_renewable_profiles` script.
We should activate them and test their functionality.

### PR DESCRIPTION
**Pull request by davide-f**
# Closes #39 and #108

## Changes proposed in this Pull Request
Validate and improve hydro representation

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
With the latest fix, now inflows are non-zero for all powerplants in NG (tested for the dams or storage_units)
image

**Comment by davide-f** [comment]
I've validated the hydro energy production; I may modify an existing script to show that.
Currently, the solution for Nigeria leads to 5.56TWh of energy production. According to IEA, in 2013 (we use the cutout of 2013), the hydro energy production was 19174 TJ (https://www.iea.org/countries/nigeria) which are 5.33TWh.
I think we can consider almost finalized this problem.

Any opinions?

**Comment by davide-f** [comment]
I think this PR is in very good shape.
As you can see in the [new hydro notebook](https://github.com/pypsa-meets-africa/pypsa-africa/blob/8b940a28064b6602c56b04ec343b02ced5222f9a/notebooks/validation/hydro_generation_validation.ipynb), total energy production by hydro does not match the expected value (130TWh vs our 77TWh), the error is too large.
With respect to PyPSA-Eur, we do not do the inflow normalization, which may be needed and I think it is just the missing step.

That can be done in this PR or a new one, however, it is important to review the current PR that has the following new features:
- Improved hydro_capacities
- Validation notebook for hydro energy production
- Crosscheck and bugfixing for hydro energy production
- Other minor bug fixing

**Comment by pz-max** [comment]
@davide-f cool that you also repaired the CI :D
Great validation script. Yes, we are slightly off +-40%...
Before I am merging this PR due to other useful corrections happening:
- crs addition, snakemake fix, default.config fix

Can you add a release_note?

Further, can you create a new issue that addresses "Add hydro inflow normalization" or something like that?

**Review by pz-max — APPROVED** [review]
release note missing

**Comment by davide-f** [comment]
Release note added and opening the new issue

**Comment by pz-max** [comment]
Awesome :dancers:

**Pull request merged**
