### PR TITLE
feat: remove "scripts." in snakefile

### PR DESCRIPTION
**Pull request by doneachh**
# Closes # (if applicable).

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by doneachh** [comment]
Hi @davide-f ,
I adjusted the snakefile in pypsa-earth as you told me in the PR of pypsa-earth sec:
https://github.com/pypsa-meets-earth/pypsa-earth-sec/pull/237
As we do not work with paths in the get_commit function of pypsa-earth, i didn't adjust that here or do you think it's necessary? :)

PS: Do you know, why the pipeline doesnt work? Is it still because of the zenodo issue or is it because of my adjustments?

**Comment by davide-f** [comment]
> Hi @davide-f , I adjusted the snakefile in pypsa-earth as you told me in the PR of pypsa-earth sec: [pypsa-meets-earth/pypsa-earth-sec#237](https://github.com/pypsa-meets-earth/pypsa-earth-sec/pull/237) As we do not work with paths in the get_commit function of pypsa-earth, i didn't adjust that here or do you think it's necessary? :)
> 
> PS: Do you know, why the pipeline doesnt work? Is it still because of the zenodo issue or is it because of my adjustments?

Great @doneachh :D
So, I'd parse here the changes on the function you implemented in the -sec version.
In the future, we may use just this function also in the -sec version.

Could you parse the changes here?

I'd like a CI to work to merge this PR, we can launch a CI early tomorrow, or if you commit early tomorrow, that should do the trick in the meantime...

**Review by davide-f — COMMENTED** [review]
On top of the above, please, there is a missing "scripts." in:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/726c01050f32231adf647d84d537be8ad77be1d4/Snakefile#L1046

**Comment by doneachh** [comment]
Hi @davide-f :D
I adjusted the code as described :)

**Comment by davide-f** [comment]
CI passing, merging :)
@doneachh, after merging in the -sec version, please update the git submodule using `git submodule update --remote --merge`

you may investigate if we can use the get_commit function from the pypsa-earth submodule instead of copying it into the -sec version, but that's not necessary

Great :D

**Pull request merged**
