### PR TITLE
Fix displaying the options wildcard in read-the-docs

### PR DESCRIPTION
**Pull request by ekatef**
Currently, the configtable for options is not displayed in our documantation due to parsing errors:

https://pypsa-earth.readthedocs.io/en/latest/wildcards.html#the-opts-wildcard

## Changes proposed in this Pull Request

Fixed format of `opts.csv` configtable.

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
Cool @ekatef :)
For me this is fine and I believe no conflicts should appear with #918 : in #918 no changes are (yet) included on that file.
Since you are investigating that PR, do you foresee changes on the opts file?
If not, we can merge this PR

**Comment by ekatef** [comment]
> Cool @ekatef :) For me this is fine and I believe no conflicts should appear with #918 : in #918 no changes are (yet) included on that file. Since you are investigating that PR, do you foresee changes on the opts file? If not, we can merge this PR

Thanks a lot @davide-f!
As a second thought, #918 is focused on improving explanations for installation and tutorials, which shouldn't go into configtables. So, agree that the conflicts with this PR are not likely 🙂

**Comment by davide-f** [comment]
Super :)
Merging

**Comment by ekatef** [comment]
> Super :) Merging

Thanks a lot!!

**Pull request merged**
