### PR TITLE
Update default year for IRENA RES scaling

### PR DESCRIPTION
**Pull request by cpschau**
## Changes proposed in this Pull Request

This PR updates the default year for RES capacity estimation based on the latest IRENA data (`electricity:estimate_renewable_capacities:year`), that happens in `add_electricity.py`. Additionally, the configuration table and the corresponding comment in `config.default.yaml` have been adjusted accordingly.

The IRENA data used in powerplantmatching now includes information up to 2023 (https://github.com/PyPSA/powerplantmatching/blob/9a63ed0363e748a6967673c00cb2a6dd7d6c80c4/powerplantmatching/package_data/config.yaml#L64). For the case of Brazil this update entails significant changes in capacity (onshore wind: 17.2 GW -> 29.1 GW; solar: 8.4 GW -> 37.4 GW).

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [x] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
Great @cpschau :D
Many thanks for the contribution! This is neat and ready-to-be-merged.
Does this PR requires the new powerplantmatching version to have the updated IRENA data?

**Comment by cpschau** [comment]
> Great @cpschau :D Many thanks for the contribution! This is neat and ready-to-be-merged. Does this PR requires the new powerplantmatching version to have the updated IRENA data?

Hey @davide-f ,

the IRENA update was introduced in the [PPM release v0.5.13](https://github.com/PyPSA/powerplantmatching/releases/tag/v0.5.13), so not so new anymore :smiley:

**Comment by davide-f** [comment]
> > Great @cpschau :D Many thanks for the contribution! This is neat and ready-to-be-merged. Does this PR requires the new powerplantmatching version to have the updated IRENA data?
> 
> Hey @davide-f ,
> 
> the IRENA update was introduced in the [PPM release v0.5.13](https://github.com/PyPSA/powerplantmatching/releases/tag/v0.5.13), so not so new anymore 😃

This looks good to me!
We have a problem with powerplantmatching because the Global Energy Monitoring has changed permission access to the data.
This problem is solved with the new powerplantmatching version.
Would you mind to add such constraint? powerplantmatching>=0.6?

**Comment by cpschau** [comment]
> > > Great @cpschau :D Many thanks for the contribution! This is neat and ready-to-be-merged. Does this PR requires the new powerplantmatching version to have the updated IRENA data?
> > 
> > 
> > Hey @davide-f ,
> > the IRENA update was introduced in the [PPM release v0.5.13](https://github.com/PyPSA/powerplantmatching/releases/tag/v0.5.13), so not so new anymore 😃
> 
> This looks good to me! We have a problem with powerplantmatching because the Global Energy Monitoring has changed permission access to the data. This problem is solved with the new powerplantmatching version. Would you mind to add such constraint? powerplantmatching>=0.6?

Done!

**Comment by davide-f** [comment]
As CI successds, this is merged :D

**Comment by davide-f** [comment]
@FabianHofmann currently the CIs are experiencing issues with the installation of micromamba.
This applies here and also https://github.com/pypsa-meets-earth/pypsa-earth/pull/1113 but with different reasons.
Is there a reason why using micromamba instead of conda given the issues?
mamba was performing better in resolving the envs, but conda seemed to have moved to mamba libs for that.
Shall we revise and/or open an issue?

**Comment by davide-f** [comment]
Note, this is a reported issue with the latest micromamba update:
https://github.com/mamba-org/micromamba-releases/issues/58

FYI @finozzifa

**Comment by davide-f** [comment]
@cpschau FYI I removed the constraint on powerplantmatching to let the CI run, ready to merge as it completes :)

**Pull request merged**
