### PR TITLE
Functionality to update costs parameters using config

### PR DESCRIPTION
**Pull request by yerbol-akhmetov**
## Changes proposed in this Pull Request

Good day. Here, I propose to add functionality to update costs parameters, such as investment, VOM, FOM, lifetime, efficiency, and fuel, using the config. These changes are inspired by `chp_cc` branch of `pypsa/pypsa-eur` and `instrat_specific_changes` branch of `open-energy-transition/pypsa-eur`. These functionality is very helpful when giving custom costs for different scenarios

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by yerbol-akhmetov** [comment]
Hi, @davide-f, this PR implements modifications of costs parameters, which is useful for analysis for different scenarios and for different horizons. Can you please look at it? In terms of code, we have already used functionality in different projects. Tested it locally, everything worked fine. 

I would like to add documentation about it into `Configuration` section of PyPSA-Earth documentation. Also maybe we can add lines into default or tutorial config to show users that such costs modifications are possible. We make those lines commented. 
image

**Comment by yerbol-akhmetov** [comment]
@davide-f, this functionality is currently implemented as `marginal_cost` and `capital_cost` modifications. I have a question about marginal costs in `config.default.yaml`. There we see solar, onwind, and other technologies are already set to replace calculated values. Are these arbitrary numbers? Any to have config set it?

**Review by davide-f — COMMENTED** [review]
Thanks @yerbol-akhmetov ! Great contribution!
The functionality is indeed quite useful and can definitely help many users!
We have had requests for changing costs and this can definitely hell!

Coding wise, it seems quite neat.
Probably documentation is needed in the form of:
- make sure the config files are updated accordingly; in a test file, it would be good to add the feature so that it's tested too
- the documentation is updated to suggest this procedure. In particular, both the docstring at the beginning of add_electricity shall be revised as well as the tutorial/default configuration

However, it would be good to have a comment by @FabianHofmann and/or @ekatef 
Changes to config files are likely conflicting to the merge.
It would be good to check how to handle that.

Options:
- add the functionality with minimal changes now to the config file and revise the config later. At least little documentation is needed though
- add this PR after the merge with all functionalities

Both options are viable to me; what would you prefer? If you have proposals feel free to add :)

**Comment by davide-f** [comment]
> @davide-f, this functionality is currently implemented as `marginal_cost` and `capital_cost` modifications. I have a question about marginal costs in `config.default.yaml`. There we see solar, onwind, and other technologies are already set to replace calculated values. Are these arbitrary numbers? Any to have config set it?

Interesting point.
These values are legacy ones. They have been there for long time and especially for wind and solar they are meant to avoid weird behavior when renewable curtailment occur.
As they have low marginal cost, the solver will curtail exceeding res quantities.
Otherwise, the same effect may be found by the solver by increasing losses in some components with weird dispatch results.

If you have comments on their numerical values, feel free to comment :D

**Comment by yerbol-akhmetov** [comment]
> Thanks @yerbol-akhmetov ! Great contribution! The functionality is indeed quite useful and can definitely help many users! We have had requests for changing costs and this can definitely hell!
> 
> Coding wise, it seems quite neat. Probably documentation is needed in the form of:
> 
> * make sure the config files are updated accordingly; in a test file, it would be good to add the feature so that it's tested too
> * the documentation is updated to suggest this procedure. In particular, both the docstring at the beginning of add_electricity shall be revised as well as the tutorial/default configuration
> 
> However, it would be good to have a comment by @FabianHofmann and/or @ekatef Changes to config files are likely conflicting to the merge. It would be good to check how to handle that.
> 
> Options:
> 
> * add the functionality with minimal changes now to the config file and revise the config later. At least little documentation is needed though
> * add this PR after the merge with all functionalities
> 
> Both options are viable to me; what would you prefer? If you have proposals feel free to add :)

To my mind, we can add these functionality as commented to tutorial and default configuration files. So they will not have an effect, but will be visible for users. 

Regarding documentation, I thought it needs to be added into [here](https://pypsa-earth.readthedocs.io/en/latest/configuration.html).  
image

Can you elaborate on test? Do you mean custom test that are performed using github CI?
image

**Comment by yerbol-akhmetov** [comment]
Hi, @davide-f. I have added documentation into `Configuration` page. In addition, I have added the option into `config.default.yaml` and `config.tutorial.yaml` as commented lines with example. I think it is important to have such so users can see such functionality (not everyone looks into the documentation directly). Or we can add lines in config files to check for Documentation. Either way may work, but the current version seems more illustrative. What are your thoughts?

**Review by davide-f — APPROVED** [review]
Great :D Fine for me :)

**Pull request merged**
