### PR TITLE
Implement OSM and PPM matching

### PR DESCRIPTION
**Pull request by ekatef**
Is intended to include power generation data extracted from OpenStreetMaps data and resolves a [building power plants issue](https://github.com/pypsa-meets-africa/pypsa-africa/issues/154). 

The assumptions are put into the docstring.

@pz-max @davide-f many thanks for your support.

### CODE REVIEW

**Comment by davide-f** [comment]
Thank you @ekatef for your contribution!!!

Before our review, please, there are some restyling suggested by linter; you can see the pull request #168 that aims at automatically fixing such changes.
Please incorporate in your local branch before the revision. 

Moreover, there may be some conflicts that you shall manually fix, but they seem minor.

Thank you! I look forward to see the final revision.

**Comment by ekatef** [comment]
@davide-f Great, thank you for the guidance! That is the first time I'm using automated style checking. Which works wonderful :)

I have implemented restyling fixes but it seems that my rights are insufficient to resolve a conflict...

**Comment by pz-max** [comment]
Hi @ekatef  , great stuff. :) Just removed a little merge conflict. 
Let's wait for the CI check & @davide-f approval for the merge.

**Comment by ekatef** [comment]
Hey @pz-max, thank you!

**Comment by davide-f** [comment]
Awesome! I merge it and i really look forward for testing it for the entire workflow :)

**Pull request merged**
