### PR TITLE
Resolved conflict with packages 

### LINKED ISSUE #936: Earth-OSM latest version(0.2.0) not compatible
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

The current update with earth-osm v0.1.0 is not compatible with the current pypsa-earth installation

This image is from the download_osm_script https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/scripts/download_osm_data.py#L109-L119
image

This image is from earth-osm repo https://github.com/pypsa-meets-earth/earth-osm/blob/main/earth_osm/eo.py#L88-L109
image

## Error Message
Terminal output
```bash
ERROR:_helpers:An error happened in module '/Users/gbotemi/Documents/code/PYPSA/mc/pypsa-earth/scripts/download_osm_data.py', function '<module>': get_osm_data() got an unexpected keyword argument 'region_list'
Traceback (most recent call last):
  File "/Users/gbotemi/Documents/code/PYPSA/mc/pypsa-earth/.snakemake/scripts/tmprd57evk9.download_osm_data.py", line 113, in <module>
    eo.get_osm_data(
TypeError: get_osm_data() got an unexpected keyword argument 'region_list'
```

### PR DESCRIPTION
**Pull request by GbotemiB**
# Closes [936](https://github.com/pypsa-meets-earth/pypsa-earth/issues/936)# (if applicable).

## Changes proposed in this Pull Request
This PR suggests a fix for the environment file due to the recent update with earth-osm. 

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
Mmm nice to fix the issue!
As a comment, maybe the function has changed name, could you check:
https://github.com/pypsa-meets-earth/earth-osm/blob/714ab0d9762d3715fdd1ebb1eba6af1773070004/earth_osm/eo.py#L122

**Comment by davide-f** [comment]
Hello @GbotemiB!
I investigated the problem and completely agree that a quick fix is recommended.
Please, could you:
- revert the change in the file environment.fixed: never edit that file during PRs, it is only updated after a new version
- please, instead of fiing the xarray with ==, please use "<=". Is that fix necessary?

Once that is done, we can merge this PR :)

When do you think you could do this?
Unfortunately I may need this today but I could step in if you agree

**Review by davide-f — COMMENTED** [review]
As discussed

**Comment by GbotemiB** [comment]
> Hello @GbotemiB! I investigated the problem and completely agree that a quick fix is recommended. Please, could you:
> 
> * revert the change in the file environment.fixed: never edit that file during PRs, it is only updated after a new version
> * please, instead of fiing the xarray with ==, please use "<=". Is that fix necessary?
> 
> Once that is done, we can merge this PR :)
> 
> When do you think you could do this? Unfortunately I may need this today but I could step in if you agree

Thanks @davide-f, I will make the changes as soon as possible.

**Comment by GbotemiB** [comment]
Hello @davide-f, I have reviewed the `yaml` files.

**Comment by GbotemiB** [comment]
I have also reset, the history to make it cleaner. If you need to make additional changes before merging, please feel free to.

Thanks @davide-f.

**Pull request merged**
